// Text-only extraction from the user's published recap pages. Never execute source HTML.
export type SourceSection={title:string;text:string};
export type Day={date:string;label:string;summary:string;url?:string;title?:string;cycle?:string;updatedAt?:string;sections?:SourceSection[];metrics?:Record<string,string>};
export type Point={date:string;name:string;strength:number|null;state:string;raw:string;sourceDate?:string;url?:string;next?:string;judgment?:string};
export type Archive={version:number;latest:string;days:Day[];points:Point[];source:string;syncNote?:string;conflicts:{date:string;name:string;previous:string;current:string;sourceDate:string}[]};
export const publicRoot='https://travelstocks.github.io/daily-trading-review/';
const entities:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};
export function plain(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ').replace(/&#(x[\da-f]+|\d+);/gi,(_,n)=>{const c=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return c>0&&c<=0x10ffff?String.fromCodePoint(c):''}).replace(/&(amp|lt|gt|quot|apos|nbsp);/g,(_,n)=>entities[n]).replace(/\s+/g,' ').trim()}
export function tables(html:string):string[][][]{return [...html.matchAll(/<table\b[^>]*>([\s\S]*?)<\/table>/gi)].map(t=>[...t[1].matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(r=>[...r[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(c=>plain(c[1]))).filter(r=>r.length))}
export function recapSections(html:string):SourceSection[]{const headings=[...html.matchAll(/<h2\b[^>]*class=["'][^"']*chapter-title[^"']*["'][^>]*>([\s\S]*?)<\/h2>/gi)];return headings.map((h,i)=>{const end=headings[i+1]?.index??html.indexOf('</main>',h.index);let fragment=html.slice(h.index!+h[0].length,end>0?end:html.length);fragment=fragment.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'');const lines=fragment.replace(/<\/(?:p|div|tr|h[1-6]|li|section|table)>/gi,'\n').replace(/<br\s*\/?\s*>/gi,'\n').split('\n').map(plain).filter(Boolean);return {title:plain(h[1]),text:lines.join('\n')}})}
export function recapPoints(html:string,sourceDate:string,url:string):Point[]{const points:Point[]=[];for(const rows of tables(html)){if(!rows[0]||!/板块|题材/.test(rows[0][0]))continue;const cols=rows[0].map((h,i)=>{const m=h.match(/(20\d{2})[./年-](\d{1,2})[./月-](\d{1,2})/);return m?{i,date:[m[1],m[2].padStart(2,'0'),m[3].padStart(2,'0')].join('-')}:null}).filter(x=>x!==null);const nextCol=rows[0].findIndex(h=>h.includes('次日'));const judgmentCol=rows[0].findIndex(h=>h.includes('核心判断'));for(const row of rows.slice(1)){for(const c of cols){const raw=row[c.i]||'',m=raw.match(/^\s*([+-]?[\d,]+(?:\.\d+)?)\s*(?:[（(]([^）)]+)[）)])?\s*$/);points.push({date:c.date,name:row[0].trim(),strength:m?Number(m[1].replaceAll(',','')):null,state:m?.[2]||'',raw,sourceDate,url,...(c.date===sourceDate?{next:row[nextCol]||'',judgment:row[judgmentCol]||''}:{})})}}}return points}
// Rank only values published in the selected day's own recap, never a later backfill.
export function topFive(points:Point[],date:string){return points.filter(p=>p.date===date&&p.sourceDate===date&&p.strength!==null&&Number.isFinite(p.strength)).sort((a,b)=>b.strength!-a.strength!||a.name.localeCompare(b.name,'zh')).filter((p,i,a)=>a.findIndex(x=>x.name===p.name)===i).slice(0,5)}
export function aroundDates(points:Point[],anchor:string,before=4,after=4){const days=[...new Set(points.map(p=>p.date).concat(anchor))].sort();const at=days.indexOf(anchor);return days.slice(Math.max(0,at-before),at+after+1)}
export function recapMetrics(html:string,date:string){const result:Record<string,string>={};for(const rows of tables(html)){const headers=rows[0];if(!headers?.includes('日期')||!headers.some(h=>/沪指|上证/.test(h)))continue;const row=rows.slice(1).find(r=>r[headers.indexOf('日期')]?.replaceAll('/','-')===date);if(!row)continue;for(let i=0;i<headers.length;i++){if(/情绪|周几|日期/.test(headers[i]))continue;const v=row[i];if(v&&!/^(None|null|未核|—|-)$/.test(v)&&!result[headers[i]])result[headers[i]]=v}}return result}
