import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const moduleUrl=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const modelUrl=moduleUrl(fs.readFileSync('app/model.ts','utf8').replace("import raw from './exam.json';",'const raw='+fs.readFileSync('app/exam.json','utf8')+';'));
const sourceUrl=moduleUrl(fs.readFileSync('app/recap-source.ts','utf8'));
const requiredUrl=moduleUrl(fs.readFileSync('app/required-candidates.ts','utf8'));
const {requiredCandidateReview,nextDayFields,leaderFields,reviewValueComplete,candidateRows}=await import(requiredUrl);
const dailyRequiredUrl=moduleUrl(fs.readFileSync('app/required-reviews.ts','utf8').replace("'./required-candidates'",JSON.stringify(requiredUrl)));
const {requiredMarketFields,requiredMarketReview,requiredDailyReviews}=await import(dailyRequiredUrl);
const reportUrl=moduleUrl(fs.readFileSync('app/report-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)).replace("'./recap-source'",JSON.stringify(sourceUrl)).replace("'./required-candidates'",JSON.stringify(requiredUrl)).replace("'./required-reviews'",JSON.stringify(dailyRequiredUrl)));
const {topFive,aroundDates,recapPoints,recapSections}=await import(sourceUrl);
const {buildReport,reportMarkdown}=await import(reportUrl);
const {emptyPaper,validatePaper,fields,markdown}=await import(modelUrl);
const mainModes=['连板接力','弱转强','分歧低吸','反核','半路','打板','趋势持股','容量核心','抱团核心','20cm','ETF','轻仓','空仓'];
assert.deepEqual(fields.get('f38').options,mainModes);
assert.equal(fields.get('f38').multi,false);
for(const mode of mainModes){
 const paper=JSON.parse(JSON.stringify({...emptyPaper(),answers:{f38:mode}}));
 assert(validatePaper(paper),`Main mode must round-trip: ${mode}`);
 assert(markdown('2026-09-23',paper).includes('**今天我的主模式**：'+mode));
}
assert(!validatePaper({...emptyPaper(),answers:{f38:['轻仓','反核']}}),'Main mode remains single-select');
assert(!validatePaper({...emptyPaper(),answers:{f38:'未知模式'}}));
console.log('PASS: all 13 main modes, saved-answer compatibility, single-select validation and export');
const history=JSON.parse(fs.readFileSync('app/workspace/history.json','utf8'));
assert.deepEqual(topFive(history.points,'2026-09-22').map(p=>p.name),['AI应用','芯片','医疗','算力','并购重组']);
assert.deepEqual(topFive(history.points,'2026-09-16').map(p=>p.name),['通信','芯片','化工','算力','机器人']);
assert.equal(topFive(history.points,'2026-09-21').length,0,'Later citations must not become a same-day ranking');
assert.equal(topFive([{date:'2026-01-01',sourceDate:'2026-01-01',name:'zero',strength:0},{date:'2026-01-01',sourceDate:'2026-01-02',name:'future',strength:999},{date:'2026-01-01',sourceDate:'2026-01-01',name:'missing',strength:null}], '2026-01-01').length,1);
const dates=aroundDates(history.points,'2026-09-16',4,4);assert(dates.includes('2026-09-15')&&dates.includes('2026-09-22'));
const fixture='<h2 class="chapter-title">一、复盘总纲</h2><p>原文&amp;证据</p><script>bad()</script><h2 class="chapter-title">三、板块强度</h2><table><tr><th>大题材板块</th><th>2026/1/1</th><th>次日节奏预测</th></tr><tr><td>电力</td><td>0（强回流）</td><td>等待确认</td></tr></table></main>';
const parsed=recapPoints(fixture,'2026-01-01','https://example.test/');assert.equal(parsed[0].strength,0);assert.equal(parsed[0].next,'等待确认');assert(!recapSections(fixture)[0].text.includes('bad()'));assert(recapSections(fixture)[0].text.includes('原文&证据'));
const p=emptyPaper();p.answers={f143:'主升',f3:'QA市场判断',f135:'QA执行',f164:'执行问题',f171:'QA修正'};p.review={cycle:'QA',body:'QA复盘补充',next:'QA明日条件',sectors:[]};assert(validatePaper(p));const report=buildReport('2026-09-22',p,history),md=reportMarkdown(report);assert(report.sections.length>=13);assert(history.days.find(d=>d.date==='2026-09-22').sections.every(s=>report.sections.some(r=>r.source?.title===s.title)),'Complete report retains every source chapter');assert(md.includes('QA市场判断')&&md.includes('QA执行')&&md.includes('QA明日条件'));assert(md.includes('8048'));assert(report.sourceUrl.includes('2026.9.22'));
const empty=buildReport('1900-01-01',emptyPaper(),history);assert.equal(empty.sections.filter(s=>s.missing).length,13);assert(!empty.sourceUrl);assert(!reportMarkdown(empty).includes('8048'));
console.log('PASS: date-driven top five, changed rankings, no look-ahead, zero/missing values, before/after window, source parser, 13-module report, shared answers, no cross-date source leakage');

const autoUrl=moduleUrl(fs.readFileSync('app/autofill.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)));
const storageUrl=moduleUrl(fs.readFileSync('app/local-records.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {applyObjectiveFill}=await import(autoUrl);
const {readRecords,saveRecord,importRecords}=await import(storageUrl);
const auto=applyObjectiveFill(emptyPaper(),'2026-09-22',history);assert.equal(auto.paper.answers.f6,'6板');assert.equal(auto.paper.answers.f40,'AI应用');assert.equal(auto.changed.length,4);assert(validatePaper(auto.paper));assert(!auto.paper.answers.f5);assert(!auto.paper.answers.f60);
const manual={...auto.paper,answers:{...auto.paper.answers,f40:'手动题材',f50:''}};const refreshed=applyObjectiveFill(manual,'2026-09-22',history);assert.equal(refreshed.paper.answers.f40,'手动题材');assert.equal(refreshed.paper.answers.f50,'');assert.equal(applyObjectiveFill({...emptyPaper(),submitted:true},'2026-09-22',history).changed.length,0);assert.equal(applyObjectiveFill(emptyPaper(),'2026-09-23',history).changed.length,0);
const kv=new Map();globalThis.localStorage={getItem:k=>kv.get(k)||null,setItem:(k,v)=>kv.set(k,v)};
let saved=saveRecord('2026-09-22',auto.paper,0);assert.equal(readRecords().length,1);assert.throws(()=>saveRecord('2026-09-22',emptyPaper(),0),/另一标签页/);
const old={...emptyPaper(),answers:{f3:'旧站个人答案'}};assert.equal(importRecords({records:[{date:'2026-09-22',paper:old}]}).added,1);assert.equal(readRecords()[0].paper.answers.f3,'旧站个人答案');assert.equal(importRecords([{date:'2026-09-22',paper:manual}]).skipped,1);
assert.throws(()=>importRecords([{date:'2026-09-23',paper:old},{date:'2026-09-24',paper:{broken:true}}]));assert.equal(readRecords().length,1,'Invalid import must be atomic');
assert.throws(()=>saveRecord('2026-09-31',old,0));
console.log('PASS: objective-only fill, provenance, manual and cleared answers preserved, archived/date isolation, durable storage, revision conflict, import migration and atomic validation');

const promotionUrl=moduleUrl(fs.readFileSync('app/promotion-fill.ts','utf8'));
const {applyPromotionFill}=await import(promotionUrl);
const promotion={date:'2026-09-23',previousDate:'2026-09-22',scope:'test scope',sources:['https://www.duanxianxia.com/web/fupan'],updatedAt:'2026-09-23T10:00:00Z',rows:['2进3','3进4','4进5','5板以上'].map((label,i)=>({label,success:i===0?1:0,total:i===0?2:0,rate:i===0?0.5:null,promoted:[],failed:[]}))};
const promoted=applyPromotionFill(emptyPaper(),promotion.date,promotion);
assert(promoted.changed);assert(validatePaper(promoted.paper));assert.equal(promoted.paper.answers.f11_0_1,'1 / 2');assert.equal(promoted.paper.answers.f11_1_2,'无参赛样本，不计算晋级率');assert.equal(promoted.paper.answers.f12,undefined);
assert.equal(applyPromotionFill(promoted.paper,promotion.date,promotion).changed,false);
const corrected={...promoted.paper,answers:{...promoted.paper.answers,f11_0_1:'我的校正',f11_1_2:''}};
assert.equal(applyPromotionFill(corrected,promotion.date,promotion).paper.answers.f11_0_1,'我的校正');assert.equal(applyPromotionFill(corrected,promotion.date,promotion).paper.answers.f11_1_2,'');
assert.equal(applyPromotionFill({...emptyPaper(),submitted:true},promotion.date,promotion).changed,false);assert.equal(applyPromotionFill(emptyPaper(),'2026-09-24',promotion).changed,false);assert.equal(applyPromotionFill(emptyPaper(),promotion.date).changed,false);
assert.equal(applyPromotionFill(emptyPaper(),promotion.date,{...promotion,rows:promotion.rows.map(r=>({...r,success:99}))}).changed,false);
console.log('PASS: automatic promotion cells, factual commentary, date isolation, no subjective answers, manual/archive protection');

const deskUrl=moduleUrl(fs.readFileSync('app/desk-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)).replace("'./required-candidates'",JSON.stringify(requiredUrl)).replace("'./required-reviews'",JSON.stringify(dailyRequiredUrl)));
const {dailyIds,optionalIds,factualGroups,questionBlock,legacyAnswerGroups,blockById,answered,recapBriefs,marketMetrics,cycleWindow,recapMonths}=await import(deskUrl);
assert.equal(new Set(dailyIds).size,dailyIds.length);assert(dailyIds.every(id=>blockById.has(id)));assert.equal(dailyIds.length,16);
assert.equal(answered(emptyPaper(),dailyIds),0);assert.equal(answered({...emptyPaper(),answers:{f143:'复苏',f3:'摘要'}},dailyIds),2);
const day=history.days.find(d=>d.date==='2026-09-22');assert.equal(recapBriefs(day).length,4);assert.equal(marketMetrics(day).find(([k])=>k==='高度板')[1],'6');assert.equal(recapBriefs(undefined).length,0);assert(marketMetrics(undefined).every(([,v])=>v==='—'));
const presented=[...dailyIds,...optionalIds,...factualGroups.flatMap(g=>g.ids)];
assert.equal(new Set(presented).size,presented.length,'No field may be asked in multiple compact groups');
assert(presented.every(id=>blockById.has(id)));
assert.equal(questionBlock('f38').options,blockById.get('f38').options,'Choice values and compatibility remain unchanged');
assert.equal(questionBlock('f135').long,true);assert.equal(blockById.get('f135').label,'实际执行','Presentation must not mutate the persisted schema');
const legacyPaper={...emptyPaper(),done:[1,8],answers:{f5:'退潮',f143:'主升',f175:'空仓',f38:'轻仓',f133:'旧交易清单',f135:'新操作结果',f164:'执行问题',f66_0_1:'测试候选',f78_0_1:'旧量能证据',f116:'10%',f110:'确认后参与',f127:'失效就退出'},review:{cycle:'',body:'旧反思',next:'旧补充预案',sectors:[]}};
assert(validatePaper(legacyPaper));
const beforeProjection=JSON.stringify(legacyPaper);
const retainedLegacy=legacyAnswerGroups(legacyPaper).flatMap(g=>g.blocks.map(b=>b.id));
assert.deepEqual(new Set(retainedLegacy),new Set(['f5','f175','f133','f164','f78_0_1']));
assert.equal(JSON.stringify(legacyPaper),beforeProjection,'Compact view never migrates, rewrites, or deletes original answers');
assert.deepEqual(legacyAnswerGroups(emptyPaper()),[]);
const compactReport=buildReport('2026-09-22',legacyPaper,history);
assert(compactReport.sections[0].summary.includes('主模式：轻仓'),'Canonical answer wins over stale duplicate conclusion');
assert(compactReport.sections[9].summary.includes('参与条件：确认后参与'));
assert(compactReport.sections[9].facts.some(([k,v])=>k==='已有补充预案'&&v==='旧补充预案'));
const planOnly=buildReport('2026-09-22',{...legacyPaper,review:undefined},history);
assert(!planOnly.pending.some(s=>s.includes('个人明日预案')),'Four plan fields replace the redundant narrative question');
assert(buildReport('2026-09-22',{...emptyPaper(),answers:{f38:'轻仓'}},history).pending.some(s=>s.includes('个人明日预案')),'Incomplete plans remain marked');
assert(reportMarkdown(compactReport).includes('旧交易清单')&&markdown('2026-09-22',legacyPaper).includes('旧量能证据'),'Both exports retain removed duplicate fields');
console.log('PASS: 16 deduplicated daily questions, non-overlapping optional/factual groups, immutable legacy answers, canonical summary and single-entry plan');

assert.equal(cycleWindow(history.days,'2026-09-23','20').at(-1).date,'2026-09-22','Missing recent day keeps recent cycle context');
assert(cycleWindow(history.days,'2026-06-01','20').some(d=>d.date==='2026-06-01'));
assert.equal(cycleWindow(history.days,'2026-09-22','all').length,history.days.length);
const metrics=marketMetrics(day);assert.equal(metrics.length,13);assert.equal(new Set(metrics.map(([k])=>k)).size,13);
assert.deepEqual(metrics.filter(([k])=>['沪指量能','断板','二板','深指'].includes(k)),[['深指','13723.74（-0.05%）'],['沪指量能','21356'],['二板','17'],['断板','18']]);
const months=recapMonths(history.days);assert.equal(months[0].month,'2026-09');assert.equal(months[0].days[0].date,'2026-09-22');assert.equal(months.flatMap(m=>m.days).length,history.days.length);assert(months.every(m=>m.days.every(d=>d.date.startsWith(m.month))));
console.log('PASS: complete 13 source metrics without aliases, newest-first month directory includes every recap');

const handbook=JSON.parse(fs.readFileSync('app/handbook.json','utf8'));
assert.equal(handbook.profile.groups.length,2);assert.equal(handbook.expectation.rows.length,6);assert(handbook.expectation.rows.every(r=>r.length===5));
const knowledgeTitles=['弱修复卖点','强回流确认','大中军启动信号','退潮期禁忌','对流题材节奏','吸血题材识别','高潮次日分歧预期','一字核心带动回流','盘中三冰反核','科创共振锚','二高潮做T','恐惧反弹准备','极致高潮次日刻度','龙头分歧看后排一字','监管日后排助攻','ETF适用边界','同身位唯一性与量能确认'];
assert(knowledgeTitles.every(t=>handbook.knowledge.cards.some(c=>c.title===t&&c.text)),'All existing knowledge must survive redesigns');
assert.deepEqual(handbook.rhythm.stages.map(s=>s.cards.length),[4,4,6,6]);assert.equal(handbook.stats.length,5);
assert(handbook.research.url.startsWith(handbook.source+'pages/'));assert(handbook.cycle.image.startsWith(handbook.source+'assets/emotion-cycle.png'));
assert(handbook.knowledge.cards.every(c=>!c.emphasis||c.text.includes(c.emphasis)));
const {openingRows,openingConditions,profitModel,inputNumber}=await import(moduleUrl(fs.readFileSync('app/limit-up-model.ts','utf8')));
const near=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} differs from ${b}`);
for(const [x,low,drawdown,amp] of openingRows){const r=openingConditions(x);near(r.minLow,low);near(r.openToLow,drawdown);near(r.amp,amp);assert.equal(r.protectivePrice,undefined)}
near(openingConditions(5,10).protectivePrice,10.16);near(openingConditions(4.5).minLow,1.2);assert.equal(openingConditions(-3).clampedOpen,-2);assert.equal(openingConditions(11).clampedOpen,10);
// Golden outputs from the original skill CLI (open=3, high=9, previous close=10).
const profit=profitModel(3,9,7,10);near(profit.safe,6.57);near(profit.hard,5.496);near(profit.safePrice,10.657);near(profit.hardPrice,10.5496);assert.equal(profit.status,'强承接');
assert.equal(profitModel(3,9,6).status,'偏弱观察');assert.equal(profitModel(3,9,5).status,'不能接受');assert.equal(profitModel(3,9,profit.safe).status,'强承接');assert.equal(profitModel(3,9,profit.hard).status,'偏弱观察');
assert.equal(inputNumber(''),undefined);assert.equal(inputNumber('  '),undefined);assert.equal(inputNumber('0'),0);assert.equal(profitModel(3,9).status,undefined);assert.equal(profitModel(3,9).safePrice,undefined);assert.equal(profitModel(3,9,0).status,'不能接受');
assert.throws(()=>openingConditions(NaN));assert.throws(()=>openingConditions(5,0));assert.throws(()=>openingConditions(5,-1));assert.throws(()=>profitModel(3,3));assert.throws(()=>profitModel(3,9,10));
console.log('PASS: preserved handbook inventory, original calculator outputs, interpolation, boundary protection, optional blanks distinct from zero, invalid-input and status thresholds');

const candidateUrl=moduleUrl(fs.readFileSync('app/leader-candidates.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)).replace("'./required-candidates'",JSON.stringify(requiredUrl)));
const executionUrl=moduleUrl(fs.readFileSync('app/execution-reflection.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)));
const digestUrl=moduleUrl(fs.readFileSync('app/recap-digest.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)).replace("'./leader-candidates'",JSON.stringify(candidateUrl)).replace("'./execution-reflection'",JSON.stringify(executionUrl)));
const {baseDigest,parseDigest}=await import(digestUrl);
const html22=fs.readFileSync('scripts/fixtures/recap-2026-09-22.html','utf8'),html23=fs.readFileSync('scripts/fixtures/recap-2026-09-23.html','utf8');
const digest22=parseDigest(html22,day),digest23=parseDigest(html23,{date:'2026-09-23',label:'',summary:''});
assert.equal(digest22.headlines.market,'放量横盘，题材内部换挡。');assert.equal(digest22.headlines.emotion,'高潮后的正常分歧。');
assert.equal(digest22.scenarios.length,4);assert.deepEqual(digest22.scenarios.map(s=>s.name),['主线加强','分歧回流','退潮切换','全面退潮']);
assert(digest22.scenarios.every(s=>s.signal&&s.action&&s.exit),'Keep both entry confirmation and retreat conditions');
assert.equal(digest22.stocks.length,8);assert(digest22.stocks.some(s=>s.name==='华软科技'&&s.level==='R级风险'),'Risk-watch stocks must not be converted to buy candidates');
assert.equal(digest22.themes.length,4);assert(digest22.themes[0].ladder.some(s=>s.name==='内蒙新华'&&s.board.includes('5板')));
assert.equal(digest22.plans.length,6);assert(digest22.plans[0].entry.includes('五进六缩量转强'));assert(digest22.plans[0].maxLoss.includes('待填'),'Do not invent a position or stop-loss number');
assert.equal(digest23.date,'2026-09-23');assert.equal(digest23.scenarios.length,4);assert.notEqual(digest23.headlines.market,digest22.headlines.market);assert.notDeepEqual(digest23.plans,digest22.plans);
assert.throws(()=>parseDigest(html23,day),/日期不匹配/);assert.throws(()=>parseDigest('<title>Unknown</title>',day),/日期不匹配/);
const missing=baseDigest();assert.equal(missing.scenarios.length,0);assert.equal(missing.plans.length,0);assert(!JSON.stringify(missing).includes('内蒙新华'));
const partial=parseDigest('<body data-review-date="2026-09-22"><script type="application/json" data-plan-defaults>invalid</script></body>',day);assert.equal(partial.plans.length,0);assert.equal(partial.headlines.market,'放量横盘，题材内部换挡。');
console.log('PASS: six-part recap digest from real dated fixtures, full scenario conditions, theme ladder, original stock grades, plan risk caveats, missing-data and cross-date protection');

const leadersUrl=moduleUrl(fs.readFileSync('app/market-leaders.ts','utf8'));
const {marketLeaders}=await import(leadersUrl);
assert.deepEqual(marketLeaders(day).names,['华瓷股份']);
assert.deepEqual(marketLeaders(history.days.find(d=>d.date==='2026-09-16')).names,['闽东电力']);
const leaderDay={date:'2026-09-23',metrics:{高度板:'4'},sections:[{title:'龙头',text:'标的 身位 领涨性\n新华文轩 4板并列最高 强\n大亚圣象 4板并列最高 强\n南华生物 4板断板 失败\n澳弘电子 9天7板 当前2板'}]};
assert.deepEqual(marketLeaders(leaderDay).names,['新华文轩','大亚圣象']);
assert.equal(marketLeaders(undefined).count,null);
assert.equal(marketLeaders({...leaderDay,metrics:{}}).names.length,0);
assert.equal(marketLeaders({...leaderDay,sections:[{title:'预案',text:'明天新华文轩晋级5板'}]}).names.length,0);
const voiceUrl=moduleUrl(fs.readFileSync('app/voice-fill.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {parseVoiceFill,applyVoiceFill}=await import(voiceUrl);
const voice=parseVoiceFill('收盘周期是退潮，主线是芯片，仓位上限是两成，分歧后回流是没有。明日预案是等待确认再参与。','2026-09-23');
assert.deepEqual(voice.items.map(i=>i.id),['f143','f60','f116','f48','review.next']);
assert.equal(voice.items.find(i=>i.id==='f48').value,'没有');
const voiceBase={...emptyPaper(),answers:{f143:'原判断',f133:'已有交易'},review:{cycle:'',body:'已有复盘',next:'',sectors:[]}};
const voiceApplied=applyVoiceFill(voiceBase,voice.items,['f60','review.next']);
assert.equal(voiceApplied.answers.f143,'原判断');assert.equal(voiceApplied.answers.f60,'芯片');assert.equal(voiceApplied.review.body,'已有复盘');assert(validatePaper(voiceApplied));
assert.equal(parseVoiceFill('市场有点复杂，我还没有确定主线。','2026-09-23').items.length,0);
assert.equal(parseVoiceFill('主模式是可能空仓也可能打板','2026-09-23').items.length,0);
const voiceJson=JSON.stringify({version:1,date:'2026-09-23',answers:{f143:'退潮',f38:'空仓',unknown:'x',f76:'不确定'},review:{next:'只观察'}});
assert.equal(parseVoiceFill(voiceJson,'2026-09-23').items.length,3);
assert.throws(()=>parseVoiceFill(voiceJson,'2026-09-22'),/日期/);
assert.throws(()=>parseVoiceFill('x'.repeat(60001),'2026-09-23'),/60000/);
assert(parseVoiceFill('收盘周期是退潮，收盘周期是修复','2026-09-23').notes.some(n=>n.includes('多次')));
console.log('PASS: same-day highest-board names, tied leaders, missing/failed-board safety, voice text matching, valid JSON import, date guard and selected-only answer updates');

const contextUrl=moduleUrl(fs.readFileSync('app/market-context.ts','utf8'));
const {snapshot,matchingBoards,matchingLimitUps}=await import(contextUrl);
assert.equal(snapshot({rows:[{date:'2026-09-23',pct:2},{date:'2026-09-22',pct:0}]},'2026-09-22').pct,0);
assert.equal(snapshot({rows:[{date:'2026-09-23',pct:2}]},'2026-09-21'),undefined);
const context=JSON.parse(fs.readFileSync('public/data/market-context.json','utf8'));
const matched=matchingBoards('PCB/复合铜箔/芯片/通信',context.themes['2026-09-23']);
assert.equal(matched.length,5);assert.equal(matched.find(b=>b.name==='PCB概念').limitUps,6);
assert.equal(matched.find(b=>b.name==='PET铜箔').limitUps,null);
assert.equal(matchingBoards('高位退潮与断板反馈',context.themes['2026-09-23']).length,0);
assert(context.quotes.filter(q=>q.region==='HK').length>=8);
assert(context.quotes.every(q=>q.rows.every(r=>Number.isFinite(r.close)&&Number.isFinite(r.pct))));
console.log('PASS: historical overseas cutoff, zero/missing, HK coverage, constituent theme matching and risk-only groups');

const dx=context.limitUpDays['2026-09-23'];
assert.equal(dx.groups.find(g=>g.name==='PCB产业链').count,5);
assert.deepEqual(matchingLimitUps('PCB/复合铜箔/芯片/通信',dx.groups).map(g=>g.name),['算力/半导体产业链','PCB产业链']);
assert.equal(matchingLimitUps('房地产',dx.groups)[0].count,5);
assert.equal(matchingLimitUps('医药',dx.groups)[0].count,2);
assert.equal(matchingLimitUps('高位退潮与断板反馈',dx.groups).length,0);
assert.equal(matchingLimitUps('通信',dx.groups).length,0,'Absent independent category is not zero or semiconductor count');
assert.equal(context.limitUpDays['2026-09-25'],undefined,'Unpublished date stays empty');
assert(Object.values(context.limitUpDays).every(d=>d.groups.every(g=>g.count===new Set(g.stocks.map(s=>s.code)).size)));
console.log('PASS: Duanxianxia real-date counts, source-preserving group aliases, no false subgroup counts and complete stock reconciliation');

const themeFillUrl=moduleUrl(fs.readFileSync('app/theme-limitup-fill.ts','utf8').replace("'./market-context'",JSON.stringify(contextUrl)));
const {applyThemeLimitUpFill}=await import(themeFillUrl);
const themePaper={...emptyPaper(),answers:{f40:'芯片',f41:'用户的逻辑',f43:'硬逻辑',f45:'强'}};
const chip=applyThemeLimitUpFill(themePaper,dx.date,dx);
assert(chip.changed&&validatePaper(chip.paper));
assert.equal(chip.paper.answers.f44,'算力/半导体产业链：8 家（原始分类，未拆分或合计）');
assert.equal(chip.paper.answers.f41,'用户的逻辑');assert.equal(chip.paper.answers.f43,'硬逻辑');assert.equal(chip.paper.answers.f45,'强');
assert.equal(chip.paper.autoFill.f44.subject,'芯片');
assert(!applyThemeLimitUpFill(chip.paper,dx.date,dx).changed);
const pcb=applyThemeLimitUpFill({...chip.paper,answers:{...chip.paper.answers,f40:'PCB'}},dx.date,dx);
assert.equal(pcb.paper.answers.f44,'5 家');
assert.equal(applyThemeLimitUpFill({...pcb.paper,answers:{...pcb.paper.answers,f40:'通信'}},dx.date,dx).paper.answers.f44,'未单列');
assert.equal(applyThemeLimitUpFill({...pcb.paper,answers:{...pcb.paper.answers,f40:''}},dx.date,dx).paper.answers.f44,'');
const missingTheme=applyThemeLimitUpFill(themePaper,'2026-09-25',dx);
assert.equal(missingTheme.paper.answers.f44,'待核');assert.equal(missingTheme.paper.autoFill.f44.sourceDate,'2026-09-25');
assert.equal(applyThemeLimitUpFill(themePaper,dx.date).paper.answers.f44,'待核');
assert.equal(applyThemeLimitUpFill(chip.paper,dx.date).paper,chip.paper,'Transient missing feed preserves verified same-date data');
const changedMissing=applyThemeLimitUpFill({...chip.paper,answers:{...chip.paper.answers,f40:'医药'}},dx.date);
assert.equal(changedMissing.paper.answers.f44,'待核','Theme change must clear the old automatic count');
assert.equal(applyThemeLimitUpFill(changedMissing.paper,dx.date,dx).paper.answers.f44,'2 家');
const refreshedDay={...dx,groups:dx.groups.map(g=>g.name==='PCB产业链'?{...g,count:6,stocks:[...g.stocks,{code:'000001',name:'fixture'}]}:g)};
assert.equal(applyThemeLimitUpFill(pcb.paper,dx.date,refreshedDay).paper.answers.f44,'6 家');
for(const value of ['9 家','']){
 const manual={...chip.paper,answers:{...chip.paper.answers,f44:value}};
 assert.equal(applyThemeLimitUpFill(manual,dx.date,dx).paper,manual);
}
assert(!applyThemeLimitUpFill({...themePaper,answers:{...themePaper.answers,f44:'旧版手填'}},dx.date,dx).changed);
assert(!applyThemeLimitUpFill({...chip.paper,submitted:true},dx.date,refreshedDay).changed);
const zeroDay={...dx,groups:[{name:'芯片',count:0,stocks:[]}]};
assert.equal(applyThemeLimitUpFill(themePaper,dx.date,zeroDay).paper.answers.f44,'0 家');
assert.equal(applyThemeLimitUpFill(themePaper,dx.date,{...zeroDay,groups:[{name:'芯片',count:9,stocks:[]}]}).paper.answers.f44,'待核');
assert.equal(applyThemeLimitUpFill(themePaper,dx.date,{...dx,groups:[...dx.groups,{name:'芯片',count:0,stocks:[]}]}).paper.answers.f44,'0 家','Prefer exact classification over a broader group');
assert(!validatePaper({...chip.paper,autoFill:{f41:chip.paper.autoFill.f44}}),'Feed provenance is objective-field only');
assert(validatePaper(JSON.parse(JSON.stringify(chip.paper))));
assert(markdown(dx.date,chip.paper).includes(chip.paper.answers.f44));
const combined=applyThemeLimitUpFill(applyPromotionFill(themePaper,dx.date,promotion).paper,dx.date,dx).paper;
assert(validatePaper(combined));assert.equal(combined.answers.f11_0_1,'1 / 2');assert.equal(combined.answers.f44,chip.paper.answers.f44);
console.log('PASS: automatic theme counts, source scope, exact-date and theme isolation, source corrections, zero/missing, manual/archive protection, promotion coexistence and saved/exported values');

const {applyLeaderCandidateFill}=await import(candidateUrl);
const candidateDay={date:'2026-09-23',label:'',summary:'',url:'https://travelstocks.github.io/daily-trading-review/pages/test.html'};
const leaderHtml=fs.readFileSync('scripts/fixtures/leader-pool-2026-09-23.html','utf8');
const pool23=parseDigest(leaderHtml,candidateDay).leaderPool;
assert(pool23.available);assert.deepEqual(pool23.candidates.map(c=>c.name),['新华文轩','大亚圣象','新华传媒']);
assert.equal(pool23.candidates[0].board,'4板 并列最高','Next-day five-board target is not the current board');
assert.equal(pool23.candidates[0].theme,'文化传媒 / AI应用');
assert(pool23.candidates[1].logic.includes('条件观察'));assert(pool23.candidates[2].logic.includes('不作为主动交易候选'));
const pool22=parseDigest(fs.readFileSync('scripts/fixtures/leader-pool-2026-09-22.html','utf8'),{...candidateDay,date:'2026-09-22'}).leaderPool;
assert.equal(pool22.candidates.length,5);assert.equal(pool22.candidates[2].board,'6板');assert.equal(pool22.candidates[4].board,'原文未明确');
assert(!pool22.candidates.some(c=>c.name==='新华文轩'));
const pool24=parseDigest(fs.readFileSync('scripts/fixtures/leader-pool-2026-09-24.html','utf8'),{...candidateDay,date:'2026-09-24'}).leaderPool;
assert.deepEqual(pool24.candidates.map(c=>c.name),['天威视讯','新华传媒','南华生物','奥佳华','新华文轩']);
assert.equal(pool24.candidates[1].board,'4板一字，换手不足');assert(pool24.candidates[1].logic.includes('可参与性低'));
assert.equal(pool24.candidates[2].board,'断板后放量承接，未封板');assert.equal(pool24.candidates[3].board,'4板、量能结构较好');
assert(pool24.candidates[0].logic.includes('不是已经确认的总龙头'));
assert(!parseDigest(html23,candidateDay).leaderPool.available,'Broad watchlist alone is not an explicit candidate pool');
assert.throws(()=>parseDigest(leaderHtml,{...candidateDay,date:'2026-09-24'}),/日期不匹配/);
const leadersFilled=applyLeaderCandidateFill(combined,candidateDay.date,candidateDay,pool23);
assert(leadersFilled.changed&&validatePaper(leadersFilled.paper));assert.equal(leadersFilled.paper.answers.f66_0_1,'新华文轩');
assert.equal(leadersFilled.paper.answers.f66_1_3,'4板 并列最高');assert.equal(leadersFilled.paper.answers.f66_3_1,undefined);
assert.equal(leadersFilled.paper.answers.f11_0_1,'1 / 2');assert.equal(leadersFilled.paper.answers.f44,chip.paper.answers.f44);
assert(!leadersFilled.paper.answers.f67_0_1&&!leadersFilled.paper.answers.f70,'Do not author subsequent scoring or final judgment');
assert.equal(applyLeaderCandidateFill(leadersFilled.paper,candidateDay.date,candidateDay,pool23).changed,false);
const manualPool={...leadersFilled.paper,answers:{...leadersFilled.paper.answers,f66_0_4:'我的校正'}};
const reversed={...pool23,candidates:[...pool23.candidates].reverse()};
const retained=applyLeaderCandidateFill(manualPool,candidateDay.date,candidateDay,reversed).paper;
assert.equal(retained.answers.f66_0_1,'新华文轩');assert.equal(retained.answers.f66_0_4,'我的校正');
assert.equal(new Set([retained.answers.f66_0_1,retained.answers.f66_1_1,retained.answers.f66_2_1]).size,3,'Preserved rows must not duplicate another candidate');
const scored={...leadersFilled.paper,answers:{...leadersFilled.paper.answers,f67_0_1:'强'}};
assert.equal(applyLeaderCandidateFill(scored,candidateDay.date,candidateDay,reversed).paper.answers.f66_0_1,'新华文轩');
const cleared={...leadersFilled.paper,answers:{...leadersFilled.paper.answers,f66_0_1:''}};
assert.equal(applyLeaderCandidateFill(cleared,candidateDay.date,candidateDay,pool23).paper.answers.f66_0_1,'');
assert(!applyLeaderCandidateFill({...leadersFilled.paper,submitted:true},candidateDay.date,candidateDay,reversed).changed);
assert(!applyLeaderCandidateFill(leadersFilled.paper,'2026-09-24',candidateDay,pool23).changed);
assert(!applyLeaderCandidateFill(leadersFilled.paper,candidateDay.date,candidateDay,undefined).changed);
assert(!applyLeaderCandidateFill(leadersFilled.paper,candidateDay.date,{...candidateDay,url:'https://example.test/'},pool23).changed);
const shortened=applyLeaderCandidateFill(leadersFilled.paper,candidateDay.date,candidateDay,{available:true,candidates:pool23.candidates.slice(0,1)}).paper;
assert.equal(shortened.answers.f66_1_1,'');assert.equal(shortened.answers.f66_1_4,'');
assert(markdown(candidateDay.date,leadersFilled.paper).includes('新华文轩'));assert(validatePaper(JSON.parse(JSON.stringify(leadersFilled.paper))));
const four=applyLeaderCandidateFill(combined,candidateDay.date,candidateDay,{available:true,candidates:[...pool23.candidates,{name:'测试第四候选',theme:'测试',board:'原文未明确',logic:'仅作测试'}]}).paper;
assert.equal(Object.keys(four.autoFill).length,25);assert(validatePaper(four));
console.log('PASS: explicit recap candidate cards and legacy lists, dated source, current boards, risk qualifiers, missing values, protected rows/scores, overflow, no subjective scoring and durable export');

const {parseExecutionReflection,applyExecutionReflectionFill}=await import(executionUrl);
const executionFor=date=>parseDigest(fs.readFileSync(`scripts/fixtures/execution-${date}.html`,'utf8'),{...candidateDay,date}).execution;
const execution22=executionFor('2026-09-22'),execution23=executionFor('2026-09-23'),execution24=executionFor('2026-09-24');
for(const execution of [execution22,execution23,execution24])assert.deepEqual(Object.keys(execution),['f135','f165','f171']);
assert(execution22.f135.value.includes('半导体ETF'));assert(!execution22.f135.value.includes('做错操作'));
assert.equal(execution22.f171.value,'盘前补齐内蒙新华的最大亏损、减仓点和条件单触发逻辑。');
assert(execution23.f135.value.includes('三组条件单分批退出')&&execution23.f135.value.includes('两成多'));
assert(execution23.f165.value.includes('改进点是'));assert(execution23.f171.value.startsWith('把“走弱停止加仓”'));
assert.equal(execution24.f135.value,'南华生物：极端下探时未恐慌离场，观察承接后继续持有\n\n天威视讯：爆量炸板回封时小仓试错\n\n哈药股份：参与反核，入场质量偏差');
assert(execution24.f165.value.startsWith('哈药股份的反核前置条件不充分。'));
assert.equal(execution24.f171.value,'把“深水”“不快速拉高”“反核成功”量化为明确价格、时间和量能条件。');
assert(!execution24.f135.value.includes('周一')&&!execution24.f135.value.includes('考虑加'),'Never turn a future plan into an executed trade');
assert.deepEqual(parseExecutionReflection('<h2>日常知识总结</h2><h3>Improve</h3><p>不要套用这条通用规则</p>'),{});
assert.deepEqual(parseExecutionReflection('<h2>四、今日操作结果</h2><h3>今日操作结果</h3><p>今日未操作。</p><h2>六、明日计划</h2><h3>核心失误</h3><p>别读取下个章节</p>'),{f135:{value:'今日未操作。',section:'今日操作结果 / 操作复盘'}});
const explicitNone=parseExecutionReflection('<h2>四、今日操作结果</h2><h3>今日操作结果</h3><p>今日空仓，无交易。</p><h3>核心失误</h3><p>无。</p>');assert.equal(explicitNone.f165.value,'无。');assert(!explicitNone.f171,'No invented improvement for a missing source');
const execFilled=applyExecutionReflectionFill(leadersFilled.paper,candidateDay.date,candidateDay,execution23);
assert(execFilled.changed&&validatePaper(execFilled.paper));assert.equal(execFilled.paper.answers.f135,execution23.f135.value);
assert.equal(execFilled.paper.answers.f66_0_1,'新华文轩');assert.equal(execFilled.paper.answers.f11_0_1,'1 / 2');assert.equal(execFilled.paper.answers.f44,chip.paper.answers.f44);
assert(!execFilled.paper.answers.f1&&!execFilled.paper.answers.f2&&!execFilled.paper.answers.f38,'Do not extend transcription to account, PnL or next-day decisions');
assert(!applyExecutionReflectionFill(execFilled.paper,candidateDay.date,candidateDay,execution23).changed);
const execManual={...execFilled.paper,answers:{...execFilled.paper.answers,f135:'手动补充交易',f165:''}};
const execChanged={...execution23,f135:{value:'原文修正操作',section:'今日操作结果'},f165:{value:'原文修正失误',section:'核心失误'},f171:{value:'原文修正改进',section:'Improve'}};
const execUpdated=applyExecutionReflectionFill(execManual,candidateDay.date,candidateDay,execChanged).paper;
assert.equal(execUpdated.answers.f135,'手动补充交易');assert.equal(execUpdated.answers.f165,'');assert.equal(execUpdated.answers.f171,'原文修正改进');
assert.equal(applyExecutionReflectionFill({...emptyPaper(),answers:{f135:''}},candidateDay.date,candidateDay,execution23).paper.answers.f135,'','Respect explicitly cleared pre-sync fields too');
assert(!applyExecutionReflectionFill({...execFilled.paper,submitted:true},candidateDay.date,candidateDay,execChanged).changed);
assert(!applyExecutionReflectionFill(execFilled.paper,'2026-09-24',candidateDay,execChanged).changed);
assert(!applyExecutionReflectionFill(execFilled.paper,candidateDay.date,{...candidateDay,url:'https://example.test/'},execChanged).changed);
assert(!applyExecutionReflectionFill(execFilled.paper,candidateDay.date,candidateDay,undefined).changed);
assert(!applyExecutionReflectionFill(execFilled.paper,candidateDay.date,candidateDay,{}).changed,'Transient missing sources do not erase prior verified excerpts');
const allAuto={...four,answers:{...auto.paper.answers,...four.answers},autoFill:{...auto.paper.autoFill,...four.autoFill}};
const allWithExecution=applyExecutionReflectionFill(allAuto,candidateDay.date,candidateDay,execution23).paper;
assert.equal(Object.keys(allWithExecution.autoFill).length,32);assert(validatePaper(allWithExecution),'All 32 provenance entries must remain persistable');
assert(validatePaper(JSON.parse(JSON.stringify(execFilled.paper))));assert(markdown(candidateDay.date,execFilled.paper).includes('三组条件单分批退出'));
assert(reportMarkdown(buildReport(candidateDay.date,execFilled.paper,history)).includes(execution23.f171.value));
console.log('PASS: dated narrative/table/KISS extraction, concise source order, no invented trades or plans, manual/clear/archive guards, all 32 provenance entries and report/export persistence');

// Mandatory detail checks are submission rules, not destructive storage migrations.
assert(!optionalIds.includes('f67'),'Seven-dimensional comparison is no longer optional');
assert(requiredCandidateReview(emptyPaper()).every(g=>!g.complete));
for(const value of ['', '  ', '待补充', '待核', '—', '暂无', '无', '不确定', 'N/A'])assert(!reviewValueComplete(value),value);
assert(reviewValueComplete('待核：缺少区间偏离值，盘前核对公告和指数基准'));
assert.deepEqual(candidateRows({...emptyPaper(),answers:{f66_0_1:'无',f66_1_1:'待补充',f66_2_1:'候选测试'}}),[2]);
const requiredPaper={...emptyPaper(),answers:{f66_0_1:'必填测试A',f66_0_2:'测试题材A',f66_0_3:'3板',f66_2_1:'必填测试C',f66_2_2:'测试题材C',f66_2_3:'4板'}};
const originalRequired=JSON.stringify(requiredPaper);
assert.deepEqual(requiredCandidateReview(requiredPaper).map(g=>[g.filled,g.total]),[[0,10],[0,24]],'Only named candidates count; do not require four names');
assert.equal(JSON.stringify(requiredPaper),originalRequired);
for(const row of [0,2])for(const field of [...nextDayFields(row),...leaderFields(row)]){
 assert(fields.has(field.id),'Every rendered field must persist: '+field.id);
 requiredPaper.answers[field.id]=`${row===0?'A':'C'} ${field.label}：已记录证据和核验条件`;
}
assert(requiredCandidateReview(requiredPaper).every(g=>g.complete));
assert(validatePaper(JSON.parse(JSON.stringify(requiredPaper))));
const filledRequiredReport=buildReport('2026-09-24',requiredPaper,history);
assert.deepEqual(filledRequiredReport.sections[11].table.rows[0],[requiredPaper.answers.f66_0_1,...nextDayFields(0).map(f=>requiredPaper.answers[f.id])]);
assert.equal(filledRequiredReport.sections[11].table.rows[0].at(-1),requiredPaper.answers.f187_0_5,'Theme name is not a theme expectation');
assert.equal(filledRequiredReport.sections[12].table.headers.length,filledRequiredReport.sections[12].table.rows[0].length);
for(const row of [0,2])for(const field of [...nextDayFields(row),...leaderFields(row)]){
 assert(reportMarkdown(filledRequiredReport).includes(requiredPaper.answers[field.id]));
 assert(markdown('2026-09-24',requiredPaper).includes(requiredPaper.answers[field.id]));
 const incomplete={...requiredPaper,answers:{...requiredPaper.answers,[field.id]:'待补充'}};
 assert(requiredCandidateReview(incomplete).some(g=>!g.complete),'Each field gates submission: '+field.id);
}
assert(!filledRequiredReport.pending.some(s=>/明日核心票预期细化|龙头预备票核验/.test(s)));
assert.deepEqual(legacyAnswerGroups(requiredPaper),[],'Required fields are not duplicated in legacy/optional panels');
const orphan={...requiredPaper,answers:{...requiredPaper.answers,f66_0_1:''}};
assert(legacyAnswerGroups(orphan).some(g=>g.blocks.some(b=>b.id==='f187_0_1')),'Removing a name must not make old row answers inaccessible');
const noCandidates={...emptyPaper(),answers:{f189:'没有合格候选：同身位竞争未结束，缺少持续领涨证据',f190:'明日只观察：等分歧承接与板块带动同时确认再重新评估'}};
assert(requiredCandidateReview(noCandidates).every(g=>g.complete));
const noneReport=buildReport('2026-09-24',noCandidates,history);
assert.equal(noneReport.sections[11].facts[0][1],noCandidates.answers.f190);
assert.equal(noneReport.sections[12].facts[0][1],noCandidates.answers.f189);
assert(!noneReport.sections[11].table&&!noneReport.sections[12].table,'Do not fabricate stocks');
assert(requiredCandidateReview({...noCandidates,answers:{...noCandidates.answers,f66_0_1:'新增候选'}}).some(g=>!g.complete),'No-candidate notes do not bypass active candidates');
assert(validatePaper({...emptyPaper(),submitted:true}),'Old archives remain readable without new fields');
for(const field of [...nextDayFields(0),...leaderFields(0)]){
 const authored={...leadersFilled.paper,answers:{...leadersFilled.paper.answers,[field.id]:'已写依据'}};
 const changed=applyLeaderCandidateFill(authored,candidateDay.date,candidateDay,reversed).paper;
 assert.equal(changed.answers.f66_0_1,authored.answers.f66_0_1,'Autofill must not reassign reviewed row: '+field.id);
 assert.equal(changed.answers[field.id],'已写依据');
}
saveRecord('2026-09-24',requiredPaper,0);
assert.deepEqual(readRecords().find(r=>r.date==='2026-09-24').paper.answers,requiredPaper.answers);
assert(!readRecords().find(r=>r.date==='2026-09-22').paper.answers.f187_0_1,'New details stay in their selected date');
console.log('PASS: two daily required modules, every field gated, all report columns wired, explicit no-candidate path, source row protection, legacy compatibility, full exports and dated persistence');

assert.deepEqual(requiredMarketFields.map(f=>f.id),['f3','f36','f37']);
for(const f of requiredMarketFields){assert(dailyIds.includes(f.id));assert(!optionalIds.includes(f.id));assert(questionBlock(f.id).long);}
assert.equal(requiredDailyReviews(emptyPaper()).length,3);
const objectiveOnly={...emptyPaper(),answers:{f6:'5板'}};
assert.equal(requiredMarketReview(objectiveOnly).missing.length,3,'Highest-board fact alone cannot satisfy market analysis');
const sourceOnly=buildReport('2026-09-22',objectiveOnly,history);
assert(sourceOnly.sections[1].source);
assert(sourceOnly.pending.some(s=>s.includes('市场风格与赚钱效应解析（每日必填）')),'Source text is not the personal answer');
assert(requiredDailyReviews(noCandidates).some(g=>!g.complete),'No-candidate explanation does not bypass required market analysis');
const marketAnswers={f3:'市场风格：轮动而非主升；量能与梯队尚未同步改善',f36:'赚钱效应：仅局部前排有溢价，后排缺少跟随',f37:'亏钱效应：高位失败票承接弱，不追修复'};
const marketComplete={...noCandidates,answers:{...noCandidates.answers,...marketAnswers}};
assert(requiredDailyReviews(marketComplete).every(g=>g.complete));
for(const field of requiredMarketFields){
 for(const blank of ['','  ','待补充','无','—'])assert(!requiredMarketReview({...marketComplete,answers:{...marketComplete.answers,[field.id]:blank}}).complete);
}
assert(requiredMarketReview({...marketComplete,answers:{...marketComplete.answers,f36:'暂无明确赚钱效应：前排没有带动，待观察次日溢价'}}).complete);
const marketReport=buildReport('2026-09-24',marketComplete,history);
for(const text of Object.values(marketAnswers))assert(marketReport.sections[1].summary.includes(text));
assert(!marketReport.pending.some(s=>s.includes('每日必填')));
assert(validatePaper(JSON.parse(JSON.stringify(marketComplete))));
assert.equal(legacyAnswerGroups(marketComplete).length,0,'Existing f36/f37 reuse the required inputs, not legacy duplicates');
assert(markdown('2026-09-24',marketComplete).includes(marketAnswers.f36));
assert(reportMarkdown(marketReport).includes(marketAnswers.f37));
const priorArchive={...objectiveOnly,submitted:true};assert(validatePaper(priorArchive));
const archiveBefore=JSON.stringify(priorArchive);requiredDailyReviews(priorArchive);assert.equal(JSON.stringify(priorArchive),archiveBefore);
console.log('PASS: market style/reward/punishment required, objective/source-only gaps detected, three-module gate, old field reuse, no-candidate independence and report/export compatibility');
