import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const moduleUrl=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const modelUrl=moduleUrl(fs.readFileSync('app/model.ts','utf8').replace("import raw from './exam.json';",'const raw='+fs.readFileSync('app/exam.json','utf8')+';'));
const sourceUrl=moduleUrl(fs.readFileSync('app/recap-source.ts','utf8'));
const reportUrl=moduleUrl(fs.readFileSync('app/report-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)).replace("'./recap-source'",JSON.stringify(sourceUrl)));
const {topFive,aroundDates,recapPoints,recapSections}=await import(sourceUrl);
const {buildReport,reportMarkdown}=await import(reportUrl);
const {emptyPaper,validatePaper}=await import(modelUrl);
const history=JSON.parse(fs.readFileSync('app/workspace/history.json','utf8'));
assert.deepEqual(topFive(history.points,'2026-09-22').map(p=>p.name),['AI应用','芯片','医疗','算力','并购重组']);
assert.deepEqual(topFive(history.points,'2026-09-16').map(p=>p.name),['通信','芯片','化工','算力','机器人']);
assert.equal(topFive(history.points,'2026-09-21').length,0,'Later citations must not become a same-day ranking');
assert.equal(topFive([{date:'2026-01-01',sourceDate:'2026-01-01',name:'zero',strength:0},{date:'2026-01-01',sourceDate:'2026-01-02',name:'future',strength:999},{date:'2026-01-01',sourceDate:'2026-01-01',name:'missing',strength:null}], '2026-01-01').length,1);
const dates=aroundDates(history.points,'2026-09-16',4,4);assert(dates.includes('2026-09-15')&&dates.includes('2026-09-22'));
const fixture='<h2 class="chapter-title">一、复盘总纲</h2><p>原文&amp;证据</p><script>bad()</script><h2 class="chapter-title">三、板块强度</h2><table><tr><th>大题材板块</th><th>2026/1/1</th><th>次日节奏预测</th></tr><tr><td>电力</td><td>0（强回流）</td><td>等待确认</td></tr></table></main>';
const parsed=recapPoints(fixture,'2026-01-01','https://example.test/');assert.equal(parsed[0].strength,0);assert.equal(parsed[0].next,'等待确认');assert(!recapSections(fixture)[0].text.includes('bad()'));assert(recapSections(fixture)[0].text.includes('原文&证据'));
const p=emptyPaper();p.answers={f143:'主升',f3:'QA市场判断',f135:'QA执行',f164:'执行问题',f171:'QA修正'};p.review={cycle:'QA',body:'QA复盘补充',next:'QA明日条件',sectors:[]};assert(validatePaper(p));const report=buildReport('2026-09-22',p,history),md=reportMarkdown(report);assert(report.sections.length>=13);assert(history.days.find(d=>d.date==='2026-09-22').sections.every(s=>report.sections.some(r=>r.source?.title===s.title)),'Complete report retains every source chapter');assert(md.includes('QA市场判断')&&md.includes('QA执行')&&md.includes('QA明日条件'));assert(md.includes('8048'));assert(report.sourceUrl.includes('2026.9.22'));
const empty=buildReport('1900-01-01',emptyPaper(),history);assert.equal(empty.sections.filter(s=>s.missing).length,13);assert(!empty.sourceUrl);assert(!reportMarkdown(empty).includes('8048'));
console.log('PASS: date-driven top five, changed rankings, no look-ahead, zero/missing values, before/after window, source parser, 13-module report, shared answers, no cross-date source leakage');

const autoUrl=moduleUrl(fs.readFileSync('app/autofill.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)));
const storageUrl=moduleUrl(fs.readFileSync('app/local-records.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {applyObjectiveFill}=await import(autoUrl);
const {readRecords,saveRecord,importRecords}=await import(storageUrl);
const auto=applyObjectiveFill(emptyPaper(),'2026-09-22',history);assert.equal(auto.paper.answers.f6,'6板');assert.equal(auto.paper.answers.f40,'AI应用');assert.equal(auto.changed.length,4);assert(validatePaper(auto.paper));assert(!auto.paper.answers.f5);assert(!auto.paper.answers.f60);
const manual={...auto.paper,answers:{...auto.paper.answers,f40:'手动题材',f50:''}};const refreshed=applyObjectiveFill(manual,'2026-09-22',history);assert.equal(refreshed.paper.answers.f40,'手动题材');assert.equal(refreshed.paper.answers.f50,'');assert.equal(applyObjectiveFill({...emptyPaper(),submitted:true},'2026-09-22',history).changed.length,0);assert.equal(applyObjectiveFill(emptyPaper(),'2026-09-23',history).changed.length,0);
const kv=new Map();globalThis.localStorage={getItem:k=>kv.get(k)||null,setItem:(k,v)=>kv.set(k,v)};
let saved=saveRecord('2026-09-22',auto.paper,0);assert.equal(readRecords().length,1);assert.throws(()=>saveRecord('2026-09-22',emptyPaper(),0),/另一标签页/);
const old={...emptyPaper(),answers:{f3:'旧站个人答案'}};assert.equal(importRecords({records:[{date:'2026-09-22',paper:old}]}).added,1);assert.equal(readRecords()[0].paper.answers.f3,'旧站个人答案');assert.equal(importRecords([{date:'2026-09-22',paper:manual}]).skipped,1);
assert.throws(()=>importRecords([{date:'2026-09-23',paper:old},{date:'2026-09-24',paper:{broken:true}}]));assert.equal(readRecords().length,1,'Invalid import must be atomic');
assert.throws(()=>saveRecord('2026-09-31',old,0));
console.log('PASS: objective-only fill, provenance, manual and cleared answers preserved, archived/date isolation, durable storage, revision conflict, import migration and atomic validation');

const deskUrl=moduleUrl(fs.readFileSync('app/desk-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {dailyIds,blockById,answered,recapBriefs,marketMetrics,cycleWindow,recapMonths}=await import(deskUrl);
assert.equal(new Set(dailyIds).size,dailyIds.length);assert(dailyIds.every(id=>blockById.has(id)));assert.equal(dailyIds.length,22);
assert.equal(answered(emptyPaper(),dailyIds),0);assert.equal(answered({...emptyPaper(),answers:{f143:'复苏',f3:'摘要'}},dailyIds),2);
const day=history.days.find(d=>d.date==='2026-09-22');assert.equal(recapBriefs(day).length,4);assert.equal(marketMetrics(day).find(([k])=>k==='高度板')[1],'6');assert.equal(recapBriefs(undefined).length,0);assert(marketMetrics(undefined).every(([,v])=>v==='—'));
console.log('PASS: 22 original-field daily questions, shared progress, source-faithful briefs, missing-day metrics, complete source chapters in report');

assert.equal(cycleWindow(history.days,'2026-09-23','20').at(-1).date,'2026-09-22','Missing recent day keeps recent cycle context');
assert(cycleWindow(history.days,'2026-06-01','20').some(d=>d.date==='2026-06-01'));
assert.equal(cycleWindow(history.days,'2026-09-22','all').length,history.days.length);
const metrics=marketMetrics(day);assert.equal(metrics.length,13);assert.equal(new Set(metrics.map(([k])=>k)).size,13);
assert.deepEqual(metrics.filter(([k])=>['沪指量能','断板','二板','深指'].includes(k)),[['深指','13723.74（-0.05%）'],['沪指量能','21356'],['二板','17'],['断板','18']]);
const months=recapMonths(history.days);assert.equal(months[0].month,'2026-09');assert.equal(months[0].days[0].date,'2026-09-22');assert.equal(months.flatMap(m=>m.days).length,history.days.length);assert(months.every(m=>m.days.every(d=>d.date.startsWith(m.month))));
console.log('PASS: complete 13 source metrics without aliases, newest-first month directory includes every recap');
