import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const moduleUrl=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const modelUrl=moduleUrl(fs.readFileSync('app/model.ts','utf8').replace("import raw from './exam.json';",'const raw='+fs.readFileSync('app/exam.json','utf8')+';'));
const sourceUrl=moduleUrl(fs.readFileSync('app/recap-source.ts','utf8'));
const reportUrl=moduleUrl(fs.readFileSync('app/report-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)).replace("'./recap-source'",JSON.stringify(sourceUrl)));
const {topFive,aroundDates,recapPoints,recapSections}=await import(sourceUrl);
const {buildReport,reportMarkdown}=await import(reportUrl);
const {emptyPaper,validatePaper}=await import(modelUrl);
const history=JSON.parse(fs.readFileSync('app/workspace/history.json','utf8'));
assert.deepEqual(topFive(history.points,'2026-09-22').map(p=>p.name),['AI应用','芯片','医疗','算力','并购重组']);
assert.deepEqual(topFive(history.points,'2026-09-16').map(p=>p.name),['通信','芯片','化工','算力','机器人']);
assert.equal(topFive(history.points,'2026-09-21').length,0,'Later citations must not become a same-day ranking');
assert.equal(topFive([{date:'2026-01-01',sourceDate:'2026-01-01',name:'zero',strength:0},{date:'2026-01-01',sourceDate:'2026-01-02',name:'future',strength:999},{date:'2026-01-01',sourceDate:'2026-01-01',name:'missing',strength:null}], '2026-01-01').length,1);
const dates=aroundDates(history.points,'2026-09-16',4,4);assert(dates.includes('2026-09-15')&&dates.includes('2026-09-22'));
const fixture='<h2 class="chapter-title">一、复盘总纲</h2><p>原文&amp;证据</p><script>bad()</script><h2 class="chapter-title">三、板块强度</h2><table><tr><th>大题材板块</th><th>2026/1/1</th><th>次日节奏预测</th></tr><tr><td>电力</td><td>0（强回流）</td><td>等待确认</td></tr></table></main>';
const parsed=recapPoints(fixture,'2026-01-01','https://example.test/');assert.equal(parsed[0].strength,0);assert.equal(parsed[0].next,'等待确认');assert(!recapSections(fixture)[0].text.includes('bad()'));assert(recapSections(fixture)[0].text.includes('原文&证据'));
const p=emptyPaper();p.answers={f143:'主升',f3:'QA市场判断',f135:'QA执行',f164:'执行问题',f171:'QA修正'};p.review={cycle:'QA',body:'QA复盘补充',next:'QA明日条件',sectors:[]};assert(validatePaper(p));const report=buildReport('2026-09-22',p,history),md=reportMarkdown(report);assert(report.sections.length>=13);assert(history.days.find(d=>d.date==='2026-09-22').sections.every(s=>report.sections.some(r=>r.source?.title===s.title)),'Complete report retains every source chapter');assert(md.includes('QA市场判断')&&md.includes('QA执行')&&md.includes('QA明日条件'));assert(md.includes('8048'));assert(report.sourceUrl.includes('2026.9.22'));
const empty=buildReport('1900-01-01',emptyPaper(),history);assert.equal(empty.sections.filter(s=>s.missing).length,13);assert(!empty.sourceUrl);assert(!reportMarkdown(empty).includes('8048'));
console.log('PASS: date-driven top five, changed rankings, no look-ahead, zero/missing values, before/after window, source parser, 13-module report, shared answers, no cross-date source leakage');

const autoUrl=moduleUrl(fs.readFileSync('app/autofill.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)));
const storageUrl=moduleUrl(fs.readFileSync('app/local-records.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {applyObjectiveFill}=await import(autoUrl);
const {readRecords,saveRecord,importRecords}=await import(storageUrl);
const auto=applyObjectiveFill(emptyPaper(),'2026-09-22',history);assert.equal(auto.paper.answers.f6,'6板');assert.equal(auto.paper.answers.f40,'AI应用');assert.equal(auto.changed.length,4);assert(validatePaper(auto.paper));assert(!auto.paper.answers.f5);assert(!auto.paper.answers.f60);
const manual={...auto.paper,answers:{...auto.paper.answers,f40:'手动题材',f50:''}};const refreshed=applyObjectiveFill(manual,'2026-09-22',history);assert.equal(refreshed.paper.answers.f40,'手动题材');assert.equal(refreshed.paper.answers.f50,'');assert.equal(applyObjectiveFill({...emptyPaper(),submitted:true},'2026-09-22',history).changed.length,0);assert.equal(applyObjectiveFill(emptyPaper(),'2026-09-23',history).changed.length,0);
const kv=new Map();globalThis.localStorage={getItem:k=>kv.get(k)||null,setItem:(k,v)=>kv.set(k,v)};
let saved=saveRecord('2026-09-22',auto.paper,0);assert.equal(readRecords().length,1);assert.throws(()=>saveRecord('2026-09-22',emptyPaper(),0),/另一标签页/);
const old={...emptyPaper(),answers:{f3:'旧站个人答案'}};assert.equal(importRecords({records:[{date:'2026-09-22',paper:old}]}).added,1);assert.equal(readRecords()[0].paper.answers.f3,'旧站个人答案');assert.equal(importRecords([{date:'2026-09-22',paper:manual}]).skipped,1);
assert.throws(()=>importRecords([{date:'2026-09-23',paper:old},{date:'2026-09-24',paper:{broken:true}}]));assert.equal(readRecords().length,1,'Invalid import must be atomic');
assert.throws(()=>saveRecord('2026-09-31',old,0));
console.log('PASS: objective-only fill, provenance, manual and cleared answers preserved, archived/date isolation, durable storage, revision conflict, import migration and atomic validation');

const deskUrl=moduleUrl(fs.readFileSync('app/desk-model.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {dailyIds,blockById,answered,recapBriefs,marketMetrics,cycleWindow,recapMonths}=await import(deskUrl);
assert.equal(new Set(dailyIds).size,dailyIds.length);assert(dailyIds.every(id=>blockById.has(id)));assert.equal(dailyIds.length,22);
assert.equal(answered(emptyPaper(),dailyIds),0);assert.equal(answered({...emptyPaper(),answers:{f143:'复苏',f3:'摘要'}},dailyIds),2);
const day=history.days.find(d=>d.date==='2026-09-22');assert.equal(recapBriefs(day).length,4);assert.equal(marketMetrics(day).find(([k])=>k==='高度板')[1],'6');assert.equal(recapBriefs(undefined).length,0);assert(marketMetrics(undefined).every(([,v])=>v==='—'));
console.log('PASS: 22 original-field daily questions, shared progress, source-faithful briefs, missing-day metrics, complete source chapters in report');

assert.equal(cycleWindow(history.days,'2026-09-23','20').at(-1).date,'2026-09-22','Missing recent day keeps recent cycle context');
assert(cycleWindow(history.days,'2026-06-01','20').some(d=>d.date==='2026-06-01'));
assert.equal(cycleWindow(history.days,'2026-09-22','all').length,history.days.length);
const metrics=marketMetrics(day);assert.equal(metrics.length,13);assert.equal(new Set(metrics.map(([k])=>k)).size,13);
assert.deepEqual(metrics.filter(([k])=>['沪指量能','断板','二板','深指'].includes(k)),[['深指','13723.74（-0.05%）'],['沪指量能','21356'],['二板','17'],['断板','18']]);
const months=recapMonths(history.days);assert.equal(months[0].month,'2026-09');assert.equal(months[0].days[0].date,'2026-09-22');assert.equal(months.flatMap(m=>m.days).length,history.days.length);assert(months.every(m=>m.days.every(d=>d.date.startsWith(m.month))));
console.log('PASS: complete 13 source metrics without aliases, newest-first month directory includes every recap');

const handbook=JSON.parse(fs.readFileSync('app/handbook.json','utf8'));
assert.equal(handbook.profile.groups.length,2);assert.equal(handbook.expectation.rows.length,6);assert(handbook.expectation.rows.every(r=>r.length===5));
const knowledgeTitles=['弱修复卖点','强回流确认','大中军启动信号','退潮期禁忌','对流题材节奏','吸血题材识别','高潮次日分歧预期','一字核心带动回流','盘中三冰反核','科创共振锚','二高潮做T','恐惧反弹准备','极致高潮次日刻度','龙头分歧看后排一字','监管日后排助攻','ETF适用边界','同身位唯一性与量能确认'];
assert(knowledgeTitles.every(t=>handbook.knowledge.cards.some(c=>c.title===t&&c.text)),'All existing knowledge must survive redesigns');
assert.deepEqual(handbook.rhythm.stages.map(s=>s.cards.length),[4,4,6,6]);assert.equal(handbook.stats.length,5);
assert(handbook.research.url.startsWith(handbook.source+'pages/'));assert(handbook.cycle.image.startsWith(handbook.source+'assets/emotion-cycle.png'));
assert(handbook.knowledge.cards.every(c=>!c.emphasis||c.text.includes(c.emphasis)));
const {openingRows,openingConditions,profitModel,inputNumber}=await import(moduleUrl(fs.readFileSync('app/limit-up-model.ts','utf8')));
const near=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} differs from ${b}`);
for(const [x,low,drawdown,amp] of openingRows){const r=openingConditions(x);near(r.minLow,low);near(r.openToLow,drawdown);near(r.amp,amp);assert.equal(r.protectivePrice,undefined)}
near(openingConditions(5,10).protectivePrice,10.16);near(openingConditions(4.5).minLow,1.2);assert.equal(openingConditions(-3).clampedOpen,-2);assert.equal(openingConditions(11).clampedOpen,10);
// Golden outputs from the original skill CLI (open=3, high=9, previous close=10).
const profit=profitModel(3,9,7,10);near(profit.safe,6.57);near(profit.hard,5.496);near(profit.safePrice,10.657);near(profit.hardPrice,10.5496);assert.equal(profit.status,'强承接');
assert.equal(profitModel(3,9,6).status,'偏弱观察');assert.equal(profitModel(3,9,5).status,'不能接受');assert.equal(profitModel(3,9,profit.safe).status,'强承接');assert.equal(profitModel(3,9,profit.hard).status,'偏弱观察');
assert.equal(inputNumber(''),undefined);assert.equal(inputNumber('  '),undefined);assert.equal(inputNumber('0'),0);assert.equal(profitModel(3,9).status,undefined);assert.equal(profitModel(3,9).safePrice,undefined);assert.equal(profitModel(3,9,0).status,'不能接受');
assert.throws(()=>openingConditions(NaN));assert.throws(()=>openingConditions(5,0));assert.throws(()=>openingConditions(5,-1));assert.throws(()=>profitModel(3,3));assert.throws(()=>profitModel(3,9,10));
console.log('PASS: preserved handbook inventory, original calculator outputs, interpolation, boundary protection, optional blanks distinct from zero, invalid-input and status thresholds');

const digestUrl=moduleUrl(fs.readFileSync('app/recap-digest.ts','utf8').replace("'./recap-source'",JSON.stringify(sourceUrl)));
const {baseDigest,parseDigest}=await import(digestUrl);
const html22=fs.readFileSync('scripts/fixtures/recap-2026-09-22.html','utf8'),html23=fs.readFileSync('scripts/fixtures/recap-2026-09-23.html','utf8');
const digest22=parseDigest(html22,day),digest23=parseDigest(html23,{date:'2026-09-23',label:'',summary:''});
assert.equal(digest22.headlines.market,'放量横盘，题材内部换挡。');assert.equal(digest22.headlines.emotion,'高潮后的正常分歧。');
assert.equal(digest22.scenarios.length,4);assert.deepEqual(digest22.scenarios.map(s=>s.name),['主线加强','分歧回流','退潮切换','全面退潮']);
assert(digest22.scenarios.every(s=>s.signal&&s.action&&s.exit),'Keep both entry confirmation and retreat conditions');
assert.equal(digest22.stocks.length,8);assert(digest22.stocks.some(s=>s.name==='华软科技'&&s.level==='R级风险'),'Risk-watch stocks must not be converted to buy candidates');
assert.equal(digest22.themes.length,4);assert(digest22.themes[0].ladder.some(s=>s.name==='内蒙新华'&&s.board.includes('5板')));
assert.equal(digest22.plans.length,6);assert(digest22.plans[0].entry.includes('五进六缩量转强'));assert(digest22.plans[0].maxLoss.includes('待填'),'Do not invent a position or stop-loss number');
assert.equal(digest23.date,'2026-09-23');assert.equal(digest23.scenarios.length,4);assert.notEqual(digest23.headlines.market,digest22.headlines.market);assert.notDeepEqual(digest23.plans,digest22.plans);
assert.throws(()=>parseDigest(html23,day),/日期不匹配/);assert.throws(()=>parseDigest('<title>Unknown</title>',day),/日期不匹配/);
const missing=baseDigest();assert.equal(missing.scenarios.length,0);assert.equal(missing.plans.length,0);assert(!JSON.stringify(missing).includes('内蒙新华'));
const partial=parseDigest('<body data-review-date="2026-09-22"><script type="application/json" data-plan-defaults>invalid</script></body>',day);assert.equal(partial.plans.length,0);assert.equal(partial.headlines.market,'放量横盘，题材内部换挡。');
console.log('PASS: six-part recap digest from real dated fixtures, full scenario conditions, theme ladder, original stock grades, plan risk caveats, missing-data and cross-date protection');

const leadersUrl=moduleUrl(fs.readFileSync('app/market-leaders.ts','utf8'));
const {marketLeaders}=await import(leadersUrl);
assert.deepEqual(marketLeaders(day).names,['华瓷股份']);
assert.deepEqual(marketLeaders(history.days.find(d=>d.date==='2026-09-16')).names,['闽东电力']);
const leaderDay={date:'2026-09-23',metrics:{高度板:'4'},sections:[{title:'龙头',text:'标的 身位 领涨性\n新华文轩 4板并列最高 强\n大亚圣象 4板并列最高 强\n南华生物 4板断板 失败\n澳弘电子 9天7板 当前2板'}]};
assert.deepEqual(marketLeaders(leaderDay).names,['新华文轩','大亚圣象']);
assert.equal(marketLeaders(undefined).count,null);
assert.equal(marketLeaders({...leaderDay,metrics:{}}).names.length,0);
assert.equal(marketLeaders({...leaderDay,sections:[{title:'预案',text:'明天新华文轩晋级5板'}]}).names.length,0);
const voiceUrl=moduleUrl(fs.readFileSync('app/voice-fill.ts','utf8').replace("'./model'",JSON.stringify(modelUrl)));
const {parseVoiceFill,applyVoiceFill}=await import(voiceUrl);
const voice=parseVoiceFill('收盘周期是退潮，主线是芯片，仓位上限是两成，分歧后回流是没有。明日预案是等待确认再参与。','2026-09-23');
assert.deepEqual(voice.items.map(i=>i.id),['f143','f60','f116','f48','review.next']);
assert.equal(voice.items.find(i=>i.id==='f48').value,'没有');
const voiceBase={...emptyPaper(),answers:{f143:'原判断',f133:'已有交易'},review:{cycle:'',body:'已有复盘',next:'',sectors:[]}};
const voiceApplied=applyVoiceFill(voiceBase,voice.items,['f60','review.next']);
assert.equal(voiceApplied.answers.f143,'原判断');assert.equal(voiceApplied.answers.f60,'芯片');assert.equal(voiceApplied.review.body,'已有复盘');assert(validatePaper(voiceApplied));
assert.equal(parseVoiceFill('市场有点复杂，我还没有确定主线。','2026-09-23').items.length,0);
assert.equal(parseVoiceFill('主模式是可能空仓也可能打板','2026-09-23').items.length,0);
const voiceJson=JSON.stringify({version:1,date:'2026-09-23',answers:{f143:'退潮',f38:'空仓',unknown:'x',f76:'不确定'},review:{next:'只观察'}});
assert.equal(parseVoiceFill(voiceJson,'2026-09-23').items.length,3);
assert.throws(()=>parseVoiceFill(voiceJson,'2026-09-22'),/日期/);
assert.throws(()=>parseVoiceFill('x'.repeat(60001),'2026-09-23'),/60000/);
assert(parseVoiceFill('收盘周期是退潮，收盘周期是修复','2026-09-23').notes.some(n=>n.includes('多次')));
console.log('PASS: same-day highest-board names, tied leaders, missing/failed-board safety, voice text matching, valid JSON import, date guard and selected-only answer updates');

const contextUrl=moduleUrl(fs.readFileSync('app/market-context.ts','utf8'));
const {snapshot,matchingBoards}=await import(contextUrl);
assert.equal(snapshot({rows:[{date:'2026-09-23',pct:2},{date:'2026-09-22',pct:0}]},'2026-09-22').pct,0);
assert.equal(snapshot({rows:[{date:'2026-09-23',pct:2}]},'2026-09-21'),undefined);
const context=JSON.parse(fs.readFileSync('public/data/market-context.json','utf8'));
const matched=matchingBoards('PCB/复合铜箔/芯片/通信',context.themes['2026-09-23']);
assert.equal(matched.length,5);assert.equal(matched.find(b=>b.name==='PCB概念').limitUps,6);
assert.equal(matched.find(b=>b.name==='PET铜箔').limitUps,null);
assert.equal(matchingBoards('高位退潮与断板反馈',context.themes['2026-09-23']).length,0);
assert(context.quotes.filter(q=>q.region==='HK').length>=8);
assert(context.quotes.every(q=>q.rows.every(r=>Number.isFinite(r.close)&&Number.isFinite(r.pct))));
console.log('PASS: historical overseas cutoff, zero/missing, HK coverage, constituent theme matching and risk-only groups');
