import test from 'node:test';
import assert from 'node:assert/strict';
import {parseFeedbackQuote,feedbackMember,summarizeFeedback,buildFeedbackDay,collectPromotionFeedback} from './promotion-feedback.mjs';
import {renderFeedback} from '../public/promotion-feedback.js';
import {injectFeedback} from './render-promotion-feedback.mjs';
const stock={code:'000910',name:'大亚圣象',from:4},date='2026-09-24',previousDate='2026-09-23';
function payload(){const q=[];Object.assign(q,{2:stock.code,3:'7.6',4:'7.58',30:'20260924161451',47:'8.34'});return {code:0,data:{sz000910:{day:[[previousDate,'7.3','7.58','7.58','7.1','1'],[date,'8.34','7.60','8.34','7.43','1']],qt:{sz000910:q}}}};}
const quote=()=>parseFeedbackQuote(payload(),stock,date,previousDate,'https://example.test/quote');
test('close return and limit-price drawdown use distinct denominators',()=>{const m=feedbackMember(stock,quote(),date);assert(Math.abs(m.closePct-0.26385224274405594)<1e-9);assert(Math.abs(m.closeDrop-8.872901678657074)<1e-9);assert(Math.abs(m.maxDrop-10.911270983213438)<1e-9);});
test('daily low cannot prove a post-touch low unless opening at limit',()=>{const m=feedbackMember(stock,{...quote(),open:7.6},date);assert.equal(m.maxDrop,null);assert(m.maxDropBasis.includes('分时'));assert(Number.isFinite(m.closeDrop));});
test('unreached limit not zero drawdown and does not join touch average',()=>{const m=feedbackMember(stock,{...quote(),touched:false,high:8},date);assert.equal(m.closeDrop,null);assert.equal(m.maxDrop,null);assert.equal(summarizeFeedback([m]).dropKnown,0);});
test('wrong date, intraday quote, missing/null prices and adjusted bars cannot supply live references',()=>{const j=payload();j.data.sz000910.qt.sz000910[30]='20260925161451';assert.equal(parseFeedbackQuote(j,stock,date,previousDate,'x').closePct,null);j.data.sz000910.qt.sz000910[30]='20260924140000';assert.equal(parseFeedbackQuote(j,stock,date,previousDate,'x').touched,null);j.data.sz000910.day[1][2]='';assert.throws(()=>parseFeedbackQuote(j,stock,date,previousDate,'x'));assert.equal(feedbackMember(stock,quote(),'2026-09-25').closePct,null);});
test('equal weighted means show coverage and retain real zero, not zero-fill unknowns',()=>{const g=summarizeFeedback([{closePct:-10,touched:false},{closePct:0,touched:false},{closePct:null,touched:null}]);assert.equal(g.mean,-5);assert.equal(g.known,2);assert.equal(g.failed,3);assert.equal(summarizeFeedback([]).mean,null);});
const prev={date:previousDate,complete:true,scopeKey:'test',source:'https://example.test/p',stocks:[{...stock,boards:4},{code:'600001',name:'首板股',boards:1}]},current={date,complete:true,scopeKey:'test',source:'https://example.test/d',stocks:[]};
test('overall excludes first-board failures, ladder totals not mean-of-means',()=>{const d=buildFeedbackDay(prev,current,[previousDate,date],{[date+':'+stock.code]:quote()},'now');assert.equal(d.groups[0].failed,1);assert.equal(d.overall.failed,1);assert.equal(d.overall.mean,quote().closePct);assert.equal(d.groups[4].mean,null);assert.throws(()=>buildFeedbackDay(prev,current,[previousDate,'2026-09-23b',date],{},'now'));});
test('public renderer escapes names and embeds an idempotent dated snapshot',()=>{const d=buildFeedbackDay(prev,current,[previousDate,date],{},'now');d.groups[0].members[0].name='<img src=x onerror=alert(1)>';const rendered=renderFeedback(d);assert(!rendered.includes('<img'));assert(rendered.includes('&lt;img'));const page='<html><title>2026.9.24</title><body><h2>1.3 连板晋级与梯队</h2></body></html>',once=injectFeedback(page,date,d);assert.equal(injectFeedback(once,date,d),once);assert.throws(()=>injectFeedback(page,'2026-09-25',d));});
test('complete cached quotes survive a source outage without cross-date fallback',async()=>{const data={promotionPools:{[previousDate]:prev,[date]:current},promotionDays:{[date]:{previousDate}},promotionFeedbackQuotes:{[date+':'+stock.code]:quote()}};const result=await collectPromotionFeedback(data,new Date(),async()=>{throw Error('offline')});assert.equal(result.promotionFeedbackDays[date].overall.known,1);assert.equal(result.promotionFeedbackDays[date].groups[0].known,0);assert.equal(result.errors.length,1);});
