'use client';
import {useMemo} from 'react';
import {buildReport,reportMarkdown} from '../report-model';
import type {Paper} from '../model';
import type {Archive} from '../recap-source';
function download(name:string,text:string,type:string){const u=URL.createObjectURL(new Blob([text],{type:type+';charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export default function DailyReport({date,paper,archive,onEdit}:{date:string;paper:Paper;archive:Archive;onEdit:()=>void}){
 const report=useMemo(()=>buildReport(date,paper,archive),[date,paper,archive]);
 function exportHtml(){const content=report.sections.map(s=>'<section><h2>'+escape(s.title)+'</h2><p>'+escape(s.summary)+'</p>'+s.facts.map(([k,v])=>'<p><b>'+escape(k)+'：</b>'+escape(v)+'</p>').join('')+(s.table?'<div class="table"><table><thead><tr>'+s.table.headers.map(h=>'<th>'+escape(h)+'</th>').join('')+'</tr></thead><tbody>'+s.table.rows.map(r=>'<tr>'+r.map(v=>'<td>'+escape(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'')+(s.source?'<details><summary>同日复盘资料 · '+escape(s.source.title)+'（展开核对）</summary><p class="source">'+escape(s.source.text)+'</p></details>':'')+(s.missing?'<p>待补充：考卷与当天复盘均未提供该模块资料。</p>':'')+'</section>').join('');download(date+'-每日复盘报告.html','<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(report.title)+'</title><style>body{max-width:1100px;margin:40px auto;padding:24px;color:#20334e;font-family:system-ui;line-height:1.9}h1{font-size:28px}h2{border-bottom:1px solid #ccd5e0;padding-bottom:12px}section{margin:32px 0}p{white-space:pre-wrap}table{border-collapse:collapse;font-size:13px}td,th{padding:10px;border:1px solid #ccd5e0;text-align:left;min-width:80px}.table{overflow:auto}.source{background:#f4f6fa;padding:18px}@media print{.table{overflow:visible}td,th{min-width:0;font-size:9px;padding:4px}}</style><h1>'+escape(report.title)+'</h1><p>来源：个人考卷与同日复盘资料</p><p>原文：'+escape(report.sourceUrl||'未提供')+'</p><p>待补充：'+escape(report.pending.join('；')||'无')+'</p>'+content+'<details><summary>完整答卷底稿（全部已填字段）</summary>'+report.appendix.map(([k,v])=>'<p><b>'+escape(k)+'：</b>'+escape(v)+'</p>').join('')+'</details></html>','text/html')}
 return <article className="daily-report"><div className="report-actions"><div><h2>考卷已自动汇总为每日复盘报告</h2><p>答案和资料变更后同步重算。保留原站的复盘顺序，并补入 KISS 与考卷结论。</p></div><div><button className="secondary-button" onClick={onEdit}>补充 / 修改</button><button className="secondary-button" onClick={()=>download(date+'-每日复盘报告.md',reportMarkdown(report),'text/markdown')}>导出 Markdown</button><button className="secondary-button" onClick={exportHtml}>导出网页报告</button><button className="primary-button" onClick={()=>window.print()}>打印 / PDF</button></div></div><div className="report-cover"><p className="eyebrow">DAILY MARKET REVIEW</p><h1>{report.title}</h1><p>{report.submitted?'考卷已归档':'考卷填写中'} · 已填写 {report.answered} 项 · {report.pending.length?'仍有待补充项':'模块资料已汇总'}</p>{report.sourceUrl?<a href={report.sourceUrl} target="_blank" rel="noreferrer">同日复盘原文：{report.sourceTitle} ↗</a>:<p>尚无同日公开复盘，仅按已填写考卷汇总；不会拼接其他日期的事实。</p>}</div>{report.pending.length>0&&<aside className="report-pending"><strong>待补充与核对</strong><p>{report.pending.join('；')}。</p></aside>}<nav className="report-toc">{report.sections.map((s,i)=><a href={'#report-'+i} key={s.title}>{s.title}</a>)}</nav>{report.sections.map((s,i)=><section className="report-section" id={'report-'+i} key={s.title}><h2>{s.title}</h2>{s.summary&&<p className="report-summary">{s.summary}</p>}{s.facts.length>0&&<dl>{s.facts.map(([k,v],j)=><div key={k+j}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{s.table&&<div className="report-table"><table><thead><tr>{s.table.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{s.table.rows.map((r,j)=><tr key={j}>{r.map((v,c)=><td key={c}>{v}</td>)}</tr>)}</tbody></table></div>}{s.source&&<details className="report-source"><summary>同日复盘资料 · {s.source.title}（展开核对原文）</summary><p>{s.source.text}</p></details>}{s.missing&&<p className="missing-report">待补充：考卷与当天复盘均未提供该模块资料。</p>}</section>)}<details className="report-section"><summary>完整答卷底稿 · 全部 {report.appendix.length} 项已填内容</summary><dl>{report.appendix.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></details></article>
}
