import {useEffect,useMemo,useState} from 'react';
import {Check,ChevronDown,FileText} from 'lucide-react';
import {sections,type Paper,type Block} from '../model';
import {BlockView} from '../block-view';
import {dailyGroups,dailyIds,blockById,answered,sectionProgress} from '../desk-model';
import {marketLeaders} from '../market-leaders';
import type {Day} from '../recap-source';
import {useMarketContext} from './market-context';
import {applyPromotionFill} from '../promotion-fill';
import {applyThemeLimitUpFill} from '../theme-limitup-fill';
import {applyLeaderCandidateFill,candidateRowProtected} from '../leader-candidates';
import {useRecapDigest} from '../use-recap-digest';

export default function DailyQuestionnaire({paper,day,date,change,edit}:{paper:Paper;day?:Day;date:string;change:(k:string,v:string|string[])=>void;edit:(p:Paper)=>void}){
 const [mode,setMode]=useState('daily'),[expanded,setExpanded]=useState<number[]>([0]),[redlines,setRedlines]=useState(false);
 const leaders=useMemo(()=>marketLeaders(day),[day]);
 const {data}=useMarketContext();
 const promotion=data?.promotionDays?.[date];
 const limitUps=data?.limitUpDays?.[date];
 const {data:recap,state:recapState}=useRecapDigest(day);
 const pool=recap?.date===date?recap.leaderPool:undefined;
 const protectedRows=[0,1,2,3].filter(row=>candidateRowProtected(paper,row)).map(row=>'ABCD'[row]);
 useEffect(()=>{const promoted=applyPromotionFill(paper,date,promotion).paper;const counted=applyThemeLimitUpFill(promoted,date,limitUps).paper;const next=applyLeaderCandidateFill(counted,date,day,pool).paper;if(next!==paper)edit(next);},[paper,date,day,promotion,limitUps,pool,edit]);
 const review={cycle:'',body:'',next:'',sectors:[],...paper.review};
 function render(b:Block,j:number){const auto=b.id?paper.autoFill?.[b.id]:undefined;return <div key={b.id||j} className={b.long?'wide-field':''}>{b.id==='f11'&&<p className="auto-source">{promotion?`自动采集 · ${promotion.previousDate} → ${date}；5板以上指昨日≥5板继续晋级。判断栏为客观统计，不代填整体强弱判断。`:'系统自动采集：等待同日及上一交易日的完整涨停池，无需手写。'}{promotion&&<a href={promotion.sources[0]} target="_blank" rel="noreferrer">查看数据来源</a>}{paper.submitted&&' 已归档答卷保持原样。'}</p>}{b.id==='f66'&&<p className="auto-source">{pool?.available?`自动带入 · ${date} 每日复盘「龙头预备票」，共 ${pool.candidates.length} 只。`:(recapState||'等待同日复盘明确候选池，取得后自动填写，无需手抄。')}{pool&&pool.candidates.length>4&&<span>表格按原文顺序显示前4只；其余：{pool.candidates.slice(4).map(c=>c.name).join('、')}。完整名单见原文。</span>}<span>保留原文的条件观察、仅作锚点和不参与限制；不代填后续评分及最终判断。</span>{protectedRows.length>0&&<span>{protectedRows.join('、')} 行已有手动填写或比较评分，整行保留，避免错配候选。</span>}{paper.submitted&&<span>已归档答卷保持原样。</span>}{day?.url&&<a href={day.url} target="_blank" rel="noreferrer">查看同日复盘依据</a>}</p>}<BlockView b={b} answers={paper.answers} change={change}/>{auto&&<p className="auto-source"><Check size={13}/>{paper.answers[b.id!]===auto.value?(b.id==='f44'?(/^(待核|未单列)$/.test(auto.value)?'自动核对 · '+auto.value:'自动采集 · 涨停家数'):'已带入同日资料'):'保留你的手动修改'} · <a href={auto.sourceUrl} target="_blank" rel="noreferrer">查看来源</a><span>{auto.evidence}</span></p>}</div>}
 return <section id="exam" className="desk-exam"><div className="section-heading"><div><span className="section-kicker">第二步 / 我的判断</span><h2>决策考卷 · 写下你的判断</h2><p>已填 {answered(paper,dailyIds)} / {dailyIds.length} 个日常问题。两个视图共用原版答案，切换不会丢失内容。</p></div><a className="exam-oral-link" href="#oral-review">语音 / 整段文字填写 ↑</a></div><div className="exam-view-switch" role="group" aria-label="考卷填写视图"><button aria-pressed={mode==='daily'} onClick={()=>setMode('daily')}>日常填写 <span>{dailyIds.length} 个核心问题</span></button><button aria-pressed={mode==='full'} onClick={()=>setMode('full')}>完整考卷 <span>原版 V1.2</span></button></div>
 {mode==='daily'?<>{dailyGroups.map((g,i)=>{const source=day?.sections?.find(s=>g.source.test(s.title));return <article className="decision-module" key={g.title} id={'decision-'+i}><header><span className="module-index">0{i+1}</span><div><h3>{g.title}</h3><p>{g.subtitle}</p></div><span className="module-progress">{answered(paper,g.ids)} / {g.ids.length}</span></header><div className="decision-body"><aside className="evidence-rail"><span className="evidence-label"><FileText size={14}/>已带入的复盘资料</span>{i===0?<><div className="evidence-height"><small>当前最高板</small><strong>{paper.answers.f6||day?.metrics?.['高度板']||'待补充'}</strong><p>{leaders.names.join(' / ')||'对应个股待核实'}</p></div><p>{day?.summary||'等待同日复盘资料。'}</p></>:i===1?<div className="theme-reference">{['f40','f50','f55'].map((id,n)=><div key={id}><small>研究题材 {'ABC'[n]}</small><span>{paper.answers[id]||'待补充'}</span></div>)}</div>:null}<p className="evidence-hint">{g.hint}</p>{source&&<details><summary>核对相关原文 <ChevronDown size={13}/></summary><p className="evidence-source">{source.text}</p></details>}{day?.url&&<a href={day.url} target="_blank" rel="noreferrer">打开同日完整复盘 ↗</a>}</aside><div className="decision-fields">{g.ids.map((id,j)=>render(blockById.get(id)!,j))}{i===3&&<label className="field wide-field">明日完整预案<textarea value={review.next} maxLength={12000} onChange={e=>edit({...paper,review:{...review,next:e.target.value}})} placeholder="观察谁？满足什么条件才参与？出现什么信号退出？"/></label>}</div></div></article>})}<div className="redline-panel"><button className="disclosure-button" aria-expanded={redlines} onClick={()=>setRedlines(!redlines)}>交卷前，核对交易红线 <ChevronDown size={17}/></button>{redlines&&<div className="decision-fields">{sections.at(-1)!.blocks.map(render)}</div>}</div></>:<div className="full-exam">{sections.map((s,i)=>{const open=expanded.includes(i),progress=sectionProgress(paper,i);return <article className="full-section" key={s.title}><button className="disclosure-button" aria-expanded={open} onClick={()=>setExpanded(open?expanded.filter(x=>x!==i):[...expanded,i])}><span><small>{String(i+1).padStart(2,'0')}</small>{s.title}</span><span>{paper.done.includes(i)?'已确认':`${progress.filled} / ${progress.total} 已填`}<ChevronDown size={17}/></span></button>{open&&<div className="full-section-body"><div className="form-blocks">{s.blocks.map(render)}</div><label className="confirm-section"><input type="checkbox" checked={paper.done.includes(i)} onChange={e=>edit({...paper,done:e.target.checked?[...paper.done,i]:paper.done.filter(x=>x!==i)})}/>此部分已确认</label></div>}</article>})}</div>}
 </section>
}
