import {useId,useState} from 'react';
import {inputNumber,openingConditions,profitModel} from '../limit-up-model';
const pct=(n:number|undefined)=>n===undefined?'待输入':n.toFixed(2)+'%';
const price=(n:number|undefined)=>n===undefined?'待输入昨收价':n.toFixed(2);
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(s:string)=>void;placeholder?:string}){const id=useId();return <div className="calculator-field"><label htmlFor={id}>{label}</label><input id={id} type="number" step="any" inputMode="decimal" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></div>}
function Metrics({values}:{values:[string,string][]}){return <div className="calculator-metrics">{values.map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}
export default function LimitUpCalculator(){
 const [x,setX]=useState('5'),[close,setClose]=useState(''),[px,setPX]=useState('3'),[h,setH]=useState('9'),[p,setP]=useState(''),[pc,setPC]=useState('');
 let opening:ReturnType<typeof openingConditions>|undefined,profit:ReturnType<typeof profitModel>|undefined,openError='',profitError='';
 try{const n=inputNumber(x);if(n===undefined)throw Error('请输入开盘涨幅。');opening=openingConditions(n,inputNumber(close))}catch(e){openError=(e as Error).message}
 try{const n=inputNumber(px),high=inputNumber(h);if(n===undefined||high===undefined)throw Error('请填写开盘涨幅和第一次冲高点。');profit=profitModel(n,high,inputNumber(p),inputNumber(pc))}catch(e){profitError=(e as Error).message}
 return <section id="calculators" className="handbook-panel"><header className="handbook-heading"><div><span className="section-kicker">常用工具</span><h2>连板开盘风控与冲高回落止盈计算器</h2><p>输入百分数直接计算，例如 5 代表 5%。</p></div><a href="https://github.com/abchaoming1/limit-up-calculators-skill" target="_blank" rel="noreferrer">查看模型来源 ↗</a></header>
 <div className="calculator-grid"><article aria-label="开盘条件计算" className="calculator-card"><h3>开盘条件计算</h3><p>核对振幅阈值、最低下杀线和条件单保护价。</p><div className="calculator-fields"><Field label="开盘涨幅 x（%）" value={x} onChange={setX}/><Field label="昨日收盘价（可选）" value={close} onChange={setClose} placeholder="如 10.00"/></div><div aria-live="polite">{opening?<><Metrics values={[["振幅阈值",pct(opening.amp)],["最低下杀线",pct(opening.minLow)],["开盘到低点容忍",pct(opening.openToLow)],["条件单保护价",price(opening.protectivePrice)]]}/><p className="calculator-result">开盘 {x}% 时，模型最低下杀线为 <strong>{pct(opening.minLow)}</strong>。{opening.clamped&&<span>输入超出 [-2%, 10%]，开盘风险表已按 {opening.clampedOpen}% 边界计算。</span>}</p></>:<p className="calculator-error">{openError}</p>}</div></article>
 <article aria-label="第一次冲高回落止盈" className="calculator-card"><h3>第一次冲高回落止盈</h3><p>核对首次冲高后的安全回落线和不能接受线。</p><div className="calculator-fields"><Field label="开盘涨幅 x（%）" value={px} onChange={setPX}/><Field label="第一次冲高 h（%）" value={h} onChange={setH}/><Field label="第一次回落 p（可选，%）" value={p} onChange={setP} placeholder="如 7"/><Field label="昨日收盘价（可选）" value={pc} onChange={setPC} placeholder="如 10.00"/></div><div aria-live="polite">{profit?<><Metrics values={[["一次冲高幅度",pct(profit.impulse)],["安全回落线",pct(profit.safe)],["不能接受线",pct(profit.hard)],["安全 / 硬线价格",profit.safePrice===undefined?'待输入昨收价':`${price(profit.safePrice)} / ${price(profit.hardPrice)}`]]}/><p className="calculator-result">{profit.status?<>第一次回落到 {p}%，状态为 <strong>{profit.status}</strong>。</>:'填写第一次回落点后，显示承接状态。'}{profit.opening.clamped&&<span>开盘风险表已按 {profit.opening.clampedOpen}% 边界计算；冲高幅度和回落系数仍使用实际输入。</span>}</p></>:<p className="calculator-error">{profitError}</p>}</div></article></div>
 <p className="handbook-footnote">原模型主要用于三板及以上连板龙头。若当天爆量分歧极大，需先标记为例外日，再判断阈值是否适用；模型用于风控辅助。</p></section>
}
