import {useEffect,useMemo,useState} from 'react';
import {CartesianGrid,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowUpRight,ArrowDownRight} from 'lucide-react';
import {aroundDates,topFive,type Archive} from '../recap-source';
const colors=['#177b78','#ca7137','#416ac7','#916299','#7e8435'];
const tone=(s:string)=>/分歧|退潮|冰点/.test(s)?'cold':/回流|修复|反弹/.test(s)?'return':/高潮|主升|发酵/.test(s)?'warm':'neutral';
export default function SectorExplorer({archive,anchor}:{archive:Archive;anchor:string}){
 const [span,setSpan]=useState(4),[focus,setFocus]=useState(''),[inspect,setInspect]=useState<{date:string;name:string}|null>(null);
 useEffect(()=>{setFocus('');setInspect(null)},[anchor]);
 const top=useMemo(()=>topFive(archive.points,anchor),[archive,anchor]);
 useEffect(()=>{if(focus&&!top.some(p=>p.name===focus))setFocus('')},[top,focus]);
 const dates=useMemo(()=>aroundDates(archive.points,anchor,span,span),[archive,anchor,span]);
 const map=useMemo(()=>new Map(archive.points.map(p=>[p.date+'|'+p.name,p])),[archive]);
 const chart=dates.map(date=>Object.fromEntries([['date',date],...top.map(p=>[p.name,map.get(date+'|'+p.name)?.strength??null])]));
 const source=archive.days.find(d=>d.date===anchor),previous=[...new Set(archive.points.map(p=>p.date))].filter(d=>d<anchor).sort().at(-1);
 const inspected=inspect?map.get(inspect.date+'|'+inspect.name):null;
 return <section id="themes" className="theme-section"><div className="section-heading"><div><span className="section-kicker">题材强度与节奏</span><h2>当日最强五个题材</h2><p>{anchor} · 按当天复盘原始数值排序。选中的日期决定名单，曲线追踪这五个题材。</p></div><label className="window-select">观察窗口<select aria-label="题材观察窗口" value={span} onChange={e=>setSpan(Number(e.target.value))}><option value={4}>前后各 4 个数据日</option><option value={8}>前后各 8 个数据日</option><option value={15}>前后各 15 个数据日</option></select></label></div>
 {!top.length?<div className="desk-empty">当天没有可排名的题材强度表。发布同日复盘后会自动显示，不使用其他日期的数据替代。</div>:<div className="theme-board"><div className="theme-chart-grid"><div className="theme-ranking"><div className="ranking-heading"><span>当日排名</span><span>原始强度</span></div>{top.map((p,i)=>{const prev=previous?map.get(previous+'|'+p.name):undefined;const delta=prev?.strength!=null?p.strength!-prev.strength:null;return <button aria-pressed={focus===p.name} className={'theme-rank-row '+(focus===p.name?'focused':'')} key={p.name} onClick={()=>setFocus(focus===p.name?'':p.name)}><span className="rank-number" style={{color:colors[i]}}>0{i+1}</span><span className="rank-name"><strong>{p.name}</strong><small className={'rhythm '+tone(p.state)}>{p.state||'节奏未标注'}</small></span><span className="rank-value"><strong>{p.strength?.toLocaleString()}</strong><small className={delta!==null&&delta>=0?'delta-up':'delta-down'}>{delta===null?'无前值':<>{delta>=0?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {delta>=0?'+':'−'}{Math.abs(delta).toLocaleString()}</>}</small></span></button>})}<p className="chart-caption">变化量对比 {previous?.slice(5)||'上一数据日'}。点击题材突出对应曲线，再次点击恢复全部。</p></div><div className="theme-plot"><div className="plot-heading"><strong>{focus||'五个题材'} · 强度轨迹</strong><span>虚线为所选日 · 空值断开</span></div><div className="strength-chart"><ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={chart} margin={{top:18,right:18,bottom:8,left:0}} accessibilityLayer><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e6eae9"/><XAxis dataKey="date" tickFormatter={s=>s.slice(5)} tick={{fontSize:12,fill:'#687b81'}} minTickGap={20} axisLine={false} tickLine={false}/><YAxis width={54} tick={{fontSize:12,fill:'#687b81'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={s=>String(s)}/><ReferenceLine y={0} stroke="#b9c7cb"/><ReferenceLine x={anchor} stroke="#83989b" strokeDasharray="4 4"/>{top.map((p,i)=><Line key={p.name} dataKey={p.name} name={p.name} stroke={colors[i]} strokeOpacity={!focus||focus===p.name?1:.12} strokeWidth={focus===p.name?3:2} dot={{r:3}} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div><div className="chart-legend">{top.map((p,i)=><button key={p.name} aria-pressed={focus===p.name} onClick={()=>setFocus(focus===p.name?'':p.name)}><span style={{background:colors[i]}}/>{p.name}</button>)}</div></div></div>
 <div className="rhythm-header"><h3>分歧 → 回流 · 逐日对照</h3><p>逐日节奏按原文保留。点格子核对数值和来源。</p></div><div className="heat-scroll"><table className="heat-table"><thead><tr><th>题材 / 日期</th>{dates.map(d=><th className={d===anchor?'anchor-day':''} key={d}>{d.slice(5)}{d===anchor&&<small>所选日</small>}</th>)}</tr></thead><tbody>{top.map(p=><tr key={p.name}><th>{p.name}</th>{dates.map(d=>{const v=map.get(d+'|'+p.name);return <td className={d===anchor?'anchor-day':''} key={d}><button aria-label={`${d} ${p.name} ${v?.state||'未标注'} ${v?.strength??'无数值'}`} className={'heat-cell '+tone(v?.state||'')} disabled={!v} onClick={()=>setInspect({date:d,name:p.name})}><strong>{v?.state||'未标注'}</strong><span>{v?.strength??'—'}</span></button></td>})}</tr>)}</tbody></table></div>
 <div className="theme-source-records" aria-live="polite"><div><strong>{inspect?.date||anchor} · 原始记录</strong>{inspect&&<button onClick={()=>setInspect(null)}>返回所选日</button>}</div>{(inspect?[{name:inspect.name,point:inspected}]:top.map(p=>({name:p.name,point:p}))).map(({name,point})=><p key={name}><span>{name}：{point?.strength??'—'}（{point?.state||'未标注'}）</span>{point?.url&&<a href={point.url} target="_blank" rel="noreferrer">{point.sourceDate} 复盘{point.sourceDate!==(inspect?.date||anchor)?'（后续引用）':''} ↗</a>}</p>)}</div>
 <div className="theme-outlook">{top.filter(p=>!focus||p.name===focus).map(p=><div key={p.name}><strong>{p.name}</strong><span>{p.next||'未提供次日预期'}</span><p>{p.judgment||'未提供核心判断'}</p></div>)}</div><details className="chart-method"><summary>数据口径与来源</summary><p>名单只用所选日复盘自己的当日数值。历史走势缺值时可能采用后续复盘引用，点击格子可查来源。原始强度排名不等于主线地位或买入顺序；节奏与次日预期为原复盘观点。并列值按名称稳定排序。</p>{source?.url&&<a href={source.url} target="_blank" rel="noreferrer">核对当天复盘原文 ↗</a>}</details></div>}
 </section>
}
