'use client';
import {useMemo,useState} from 'react';
import {CartesianGrid,Legend,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {aroundDates,topFive,type Archive} from '../recap-source';
const colors=['#285bea','#b65b18','#087e8b','#983a8b','#647321'];
const tone=(s:string)=>/分歧|退潮|冰点/.test(s)?'cold':/回流|修复|反弹/.test(s)?'return':/高潮|主升|发酵/.test(s)?'warm':'neutral';
export default function SectorExplorer({archive,anchor,onAnchor}:{archive:Archive;anchor:string;onAnchor:(date:string)=>void}){
 const [span,setSpan]=useState(4),[inspect,setInspect]=useState('');
 const top=useMemo(()=>topFive(archive.points,anchor),[archive,anchor]);
 const dates=useMemo(()=>aroundDates(archive.points,anchor,span,span),[archive,anchor,span]);
 const map=new Map(archive.points.map(p=>[p.date+'|'+p.name,p]));
 const chart=dates.map(date=>Object.fromEntries([['date',date],...top.map(p=>[p.name,map.get(date+'|'+p.name)?.strength??null])]));
 const source=archive.days.find(d=>d.date===anchor);
 const previous=[...new Set(archive.points.map(p=>p.date))].filter(d=>d<anchor).sort().at(-1);
 const shown=inspect&&dates.includes(inspect)?inspect:anchor;
 return <section className="hub-card sector-explorer"><div className="card-head"><div><h2>选一天，看当天最强的五个题材</h2><p>按该日复盘表的原始强度从高到低排序。切换日期，五个题材、前后曲线和节奏一起更新。</p></div>{source?.url&&<a href={source.url} target="_blank" rel="noreferrer">当天复盘原文 ↗</a>}</div><div className="anchor-controls"><label>题材观察日期<select aria-label="题材观察日期" value={anchor} onChange={e=>{onAnchor(e.target.value);setInspect('')}}>{!archive.days.some(d=>d.date===anchor)&&<option value={anchor}>{anchor} · 尚无公开复盘</option>}{[...archive.days].sort((a,b)=>b.date.localeCompare(a.date)).map(d=><option key={d.date} value={d.date}>{d.date}</option>)}</select></label><label>观察窗口<select value={span} onChange={e=>setSpan(Number(e.target.value))}><option value={4}>前 4 / 后 4 个有数据日</option><option value={8}>前 8 / 后 8 个有数据日</option><option value={15}>前 15 / 后 15 个有数据日</option></select></label><span className="muted">排名日期：{anchor} · 数据不会倒灌到当日排名</span></div>
 {!top.length?<div className="empty-ranking"><h3>这一天没有可排名的当日题材强度表</h3><p>可以查看当日复盘原文；不会拿其他日期或个人考卷的题材来凑满五个。</p></div>:<><div className="top-five">{top.map((p,i)=>{const prev=previous?map.get(previous+'|'+p.name):undefined;const delta=prev?.strength!==null&&prev?.strength!==undefined?p.strength!-prev.strength:null;return <article key={p.name} style={{borderTopColor:colors[i]}}><span className="rank-label">TOP {i+1}</span><h3>{p.name}</h3><strong>{p.strength?.toLocaleString('zh-CN')}</strong><span className={'rhythm '+tone(p.state)}>{p.state||'未标注节奏'}</span><small>{delta===null?'上一数据日无可比值':`较 ${previous!.slice(5)} ${delta>=0?'+':''}${delta.toLocaleString('zh-CN')}`}</small><p>{p.judgment||'原文未单列核心判断'}</p><small>次日预期：{p.next||'未提供'}</small></article>})}</div>{top.length<5&&<p className="muted">原文仅有 {top.length} 个可排名题材，按实际数量显示。</p>}<p className="ranking-note">“最强五个”指原始数值前五名，不等同于主线地位或买入排序；并列值按题材名称稳定排序。原文节奏与核心判断一并保留。</p>
 <div className="card-head"><div><h2>这五个题材，前后如何演变</h2><p>虚线为 {anchor}。名单固定为所选日的前五名，向前看来路、向后看结果；空值断开。</p></div></div><div className="strength-chart"><ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={chart} margin={{top:20,right:15,bottom:8,left:8}} accessibilityLayer><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e5eaf2"/><XAxis dataKey="date" tickFormatter={s=>s.slice(5)} tick={{fontSize:12}} minTickGap={20}/><YAxis width={64} tick={{fontSize:12}}/><Tooltip labelFormatter={s=>String(s)}/><Legend/><ReferenceLine y={0} stroke="#94a3b8"/><ReferenceLine x={anchor} stroke="#172d50" strokeDasharray="5 4" label={{value:'所选日',position:'insideTopRight',fontSize:12}}/>{top.map((p,i)=><Line key={p.name} dataKey={p.name} name={p.name} stroke={colors[i]} strokeWidth={2} dot={{r:3}} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>
 <div className="card-head"><div><h2>分歧 → 回流 · 逐日对照</h2><p>每行对应所选日的一强题材。点击格子，查看该日原始值与来源。</p></div></div><div className="heat-scroll"><table className="heat-table"><thead><tr><th>题材 / 日期</th>{dates.map(d=><th className={d===anchor?'anchor-day':''} key={d}>{d.slice(5)}{d===anchor&&<small>所选日</small>}</th>)}</tr></thead><tbody>{top.map(p=><tr key={p.name}><th>{p.name}</th>{dates.map(d=>{const value=map.get(d+'|'+p.name);return <td className={d===anchor?'anchor-day':''} key={d}><button className={'heat-cell '+tone(value?.state||'')} disabled={!value} onClick={()=>setInspect(d)} title={`${d} ${p.name} · ${value?.raw||'无数据'} · 来源 ${value?.sourceDate||'无'}`}><strong>{value?.state||'未判断'}</strong><span>{value?.strength??'—'}</span></button></td>})}</tr>)}</tbody></table></div><div className="point-sources"><strong>{shown} · 原始记录</strong>{top.map(p=>{const v=map.get(shown+'|'+p.name);return <p key={p.name}>{p.name}：{v?.raw||'未提供'}{v?.url&&<> · <a href={v.url} target="_blank" rel="noreferrer">{v.sourceDate} 复盘 ↗</a>{v.sourceDate!==shown&&'（后续复盘引用）'}</>}</p>})}</div></>}
 <details className="data-note"><summary>排名与历史数据口径</summary><p>排名只使用所选日复盘自己的当日数值，不使用后续引用值，也不使用个人填写值。只有回看曲线会在当天原文缺失时采用后续复盘引用，点击格子可查来源。没有数值的题材不参与排名；零值保留。名称按原文匹配，不自动合并相近题材。</p></details></section>
}
