import handbook from '../handbook.json';
import LimitUpCalculator from './limit-up-calculator';
import './trading-handbook.css';
type Card={title:string;text:string;emphasis:string};
function CardText({card}:{card:Card}){const at=card.emphasis?card.text.indexOf(card.emphasis):-1;return <p>{at<0?card.text:<>{card.text.slice(0,at)}<em>{card.emphasis}</em>{card.text.slice(at+card.emphasis.length)}</>}</p>}
function Heading({title,note}:{title:string;note?:string}){return <header className="handbook-heading"><div><h2>{title}</h2>{note&&<p>{note}</p>}</div></header>}
export default function TradingHandbook(){return <div id="handbook" className="trading-handbook">
 <div className="handbook-intro"><div><span className="section-kicker">长期保留 · 盘前复读</span><h2>交易手册与常用工具</h2><p>沿用原复盘站的个人交易框架；与每日市场数据分开标注。</p></div><a href={handbook.source} target="_blank" rel="noreferrer">原站资料 ↗</a></div>
 <nav className="handbook-nav" aria-label="交易手册目录">{[['cycle-map','情绪周期图'],['system-profile','体系优缺点'],['expectations','隔日预期'],['knowledge','日常知识'],['theme-rhythm','题材节奏'],['research','专题研究'],['calculators','风控计算器']].map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav>
 <section id="cycle-map" className="handbook-panel"><Heading title={handbook.cycle.title} note={handbook.cycle.note}/><a className="cycle-map-link" href={handbook.cycle.image} target="_blank" rel="noreferrer" aria-label="打开完整情绪周期图"><img src={handbook.cycle.image} alt="情绪周期图：混沌期、主升期、退潮期，以及主升二阶段、三阶段的原图批注" loading="lazy"/></a><p className="handbook-footnote">保留原图全部批注。点击图片可放大查看。</p></section>
 <section id="system-profile" className="handbook-panel"><Heading title={handbook.profile.title} note={handbook.profile.note}/><div className="profile-grid">{handbook.profile.groups.map((g,i)=><article className={i?'profile-challenge':'profile-comfort'} key={g.title}><h3>{g.title}</h3><ul>{g.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></section>
 <section id="expectations" className="handbook-panel"><Heading title={handbook.expectation.title} note={handbook.expectation.note}/><div className="expectation-scroll" tabIndex={0} role="region" aria-label="隔日预期表，可左右滚动"><table><thead><tr>{handbook.expectation.headers.map(h=><th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{handbook.expectation.rows.map(row=><tr key={row[0]}>{row.map((cell,i)=>i===0?<th scope="row" key={i}>{cell}</th>:<td key={i}>{cell}</td>)}</tr>)}</tbody></table></div></section>
 <section id="knowledge" className="handbook-panel"><Heading title={handbook.knowledge.title} note={handbook.knowledge.note}/><div className="knowledge-grid">{handbook.knowledge.cards.map(card=><article className="reference-card" key={card.title}><h3>{card.title}</h3><CardText card={card}/></article>)}</div></section>
 <section id="theme-rhythm" className="handbook-panel"><Heading title={handbook.rhythm.title} note={handbook.rhythm.note}/><div className="rhythm-stages">{handbook.rhythm.stages.map(stage=><article className="rhythm-stage" key={stage.title}><h3>{stage.title}</h3><div>{stage.cards.map(card=><div className="rhythm-reference" key={card.title}><h4>{card.title}</h4><CardText card={card}/></div>)}</div></article>)}</div></section>
 <section id="research" className="handbook-panel"><span className="section-kicker">专题研究 · 龙头接力模型</span><a className="research-link" href={handbook.research.url} target="_blank" rel="noreferrer"><h2>{handbook.research.title}</h2><span>打开完整作战图 ↗</span></a><p className="research-description">{handbook.research.description}</p><div className="handbook-stats">{handbook.stats.map(s=><div key={s.label}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div><p className="handbook-footnote">原复盘站资料库统计 · 截至 {handbook.asOf}，与顶部所选日期无关。<a href={handbook.source} target="_blank" rel="noreferrer">查看资料库 ↗</a></p></section>
 <LimitUpCalculator/>
 </div>}
