import {lazy,memo,Suspense,useEffect,useRef,useState} from 'react';
import {BookOpen,Download,RefreshCw,ArrowUpRight,ChevronLeft,ChevronRight,ChevronDown,Check,Settings2} from 'lucide-react';
import {emptyPaper,validDate,chinaDate,type Paper} from '../model';
import {answer,answered,dailyIds,marketMetrics,cycleWindow} from '../desk-model';
import DailyQuestionnaire from './daily-questionnaire';
import RecapDirectory from './recap-directory';
import TradingRules from './trading-rules';
import TradingHandbook from './trading-handbook';
import RecapDigest from './recap-digest';
import {loadArchive} from '../archive-client';
import {readRecords,saveRecord,importRecords,storageKey,type Saved} from '../local-records';
import {applyObjectiveFill} from '../autofill';
import {publicRoot,type Archive} from '../recap-source';
import SectorExplorer from './sector-explorer';
const DailyReport=lazy(()=>import('./daily-report'));
const ThemeExplorer=memo(SectorExplorer);
import './workspace.css';
import './onepage.css';
import './review-layout.css';
const tone=(s:string)=>/分歧|退潮|冰点/.test(s)?'cold':/回流|修复|反弹/.test(s)?'return':/高潮|主升|发酵/.test(s)?'warm':'neutral';
function download(name:string,value:unknown){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function Workspace(){
 const [archive,setArchive]=useState<Archive|null>(null),[records,setRecords]=useState<Saved[]>([]),[date,setDate]=useState(chinaDate()),[paper,setPaper]=useState<Paper>(emptyPaper),[ready,setReady]=useState(false),[status,setStatus]=useState('正在读取资料'),[error,setError]=useState(''),[syncing,setSyncing]=useState(false),[range,setRange]=useState('20'),[sourceOpen,setSourceOpen]=useState(false),[chapter,setChapter]=useState<number|null>(0),[showReport,setShowReport]=useState(false),[importNote,setImportNote]=useState('');
 const state=useRef({date:chinaDate(),paper:emptyPaper(),revision:0,dirty:false}),readyRef=useRef(false),archiveRef=useRef<Archive|null>(null),busy=useRef(false),blocked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),file=useRef<HTMLInputElement>(null),track=useRef<HTMLDivElement>(null);
 function flush(){const s=state.current;if(!s.dirty)return true;try{if(blocked.current)throw new Error('保存已暂停。请导出当前草稿，再刷新读取最新记录。');const saved=saveRecord(s.date,s.paper,s.revision);state.current={...s,revision:saved.revision,dirty:false};setRecords(readRecords());setStatus(s.paper.submitted?'已归档 · 保存在本机':'已自动保存到本机');setError('');return true}catch(e){blocked.current=true;setError((e as Error).message);setStatus('保存失败 · 请导出草稿');return false}}
 function select(d:string,a:Archive){if(!validDate(d)||!flush())return;try{const all=readRecords();setRecords(all);const saved=all.find(r=>r.date===d);const filled=applyObjectiveFill(saved?.paper||emptyPaper(),d,a);state.current={date:d,paper:filled.paper,revision:saved?.revision||0,dirty:filled.changed.length>0};setDate(d);setPaper(filled.paper);setStatus(filled.status==='archived'?'已归档 · 保留交卷时的答案':filled.status==='waiting'?'尚无可预填的同日资料':'同日客观项已核对');flush();const url=new URL(location.href);url.searchParams.set('date',d);history.replaceState(null,'',url)}catch(e){setError((e as Error).message)}}
 async function sync(initial=false,force=false){if(busy.current)return;busy.current=true;setSyncing(true);try{const a=await loadArchive(force);archiveRef.current=a;setArchive(a);if(initial){readRecords();const q=new URLSearchParams(location.search).get('date');const d=q&&validDate(q)?q:a.latest||chinaDate();select(d,a);readyRef.current=true;setReady(true);if(location.hash)setTimeout(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView(),150)}else if(readyRef.current&&!blocked.current)select(state.current.date,a)}catch(e){setError((e as Error).message)}finally{setSyncing(false);busy.current=false}}
 useEffect(()=>{void sync(true);const id=setInterval(()=>void sync(),120000);const focus=()=>void sync();const leave=(e:BeforeUnloadEvent)=>{if(!flush()){e.preventDefault();e.returnValue=''}};const external=(e:StorageEvent)=>{if(e.key!==storageKey||!readyRef.current)return;if(state.current.dirty){blocked.current=true;setError('另一标签页已更新记录。请先导出当前草稿，再刷新读取最新记录。')}else if(archiveRef.current)select(state.current.date,archiveRef.current)};window.addEventListener('focus',focus);window.addEventListener('beforeunload',leave);window.addEventListener('storage',external);return()=>{clearInterval(id);if(timer.current)clearTimeout(timer.current);window.removeEventListener('focus',focus);window.removeEventListener('beforeunload',leave);window.removeEventListener('storage',external)}},[]);
 function edit(next:Paper){state.current={...state.current,paper:{...next,submitted:false},dirty:true};setPaper(state.current.paper);setStatus('正在保存…');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(flush,500)}
 function change(k:string,v:string|string[]){edit({...state.current.paper,answers:{...state.current.paper.answers,[k]:v}})}
 function backup(){if(!flush()){download(state.current.date+'-未保存草稿.json',{records:[{...state.current}]});return}try{download('交易日课-完整备份-'+chinaDate()+'.json',{version:1,exportedAt:new Date().toISOString(),records:readRecords()})}catch{download('交易日课-原始记录.json',localStorage.getItem(storageKey))}}
 async function importFile(f:File){if(!flush())return;try{const result=importRecords(JSON.parse(await f.text()));setImportNote(`已导入 ${result.added} 天；保留本机已有答卷 ${result.skipped} 天。`);if(archiveRef.current)select(state.current.date,archiveRef.current)}catch(e){setError((e as Error).message)}}
 const day=archive?.days.find(d=>d.date===date);
 const nodes=new Map((archive?.days||[]).map(d=>[d.date,{date:d.date,label:d.label,original:d.label,personal:false}]));
 for(const r of [...records.filter(r=>r.date!==date),{date,paper}]){const label=r.paper.answers.f143||r.paper.answers.f5;if(typeof label==='string'&&label)nodes.set(r.date,{date:r.date,label,original:nodes.get(r.date)?.original||'',personal:true})}
 const days=[...nodes.values()].sort((a,b)=>a.date.localeCompare(b.date));
 const shown=cycleWindow(days,date,range);
 const dateList=[...new Set(days.map(d=>d.date).concat(date))].sort(),dateIndex=dateList.indexOf(date);
 const metrics=marketMetrics(day),completed=answered(paper,dailyIds);
 const myCycle=answer(paper,'f143')||answer(paper,'f5');
 function goReport(){setShowReport(true);document.getElementById('report')?.scrollIntoView({behavior:'smooth'})}
 function submit(){state.current={...state.current,paper:{...state.current.paper,submitted:true},dirty:true};setPaper(state.current.paper);if(flush())goReport()}
 useEffect(()=>{const el=track.current?.querySelector<HTMLElement>('.selected');if(el&&track.current)track.current.scrollLeft=el.offsetLeft-track.current.offsetLeft-track.current.clientWidth/2+el.clientWidth/2},[date,range,ready]);
 return <div className="desk-app"><a className="skip-link" href="#recap">跳转到当日复盘</a><header className="desk-header"><a className="desk-logo" href="./"><span><BookOpen size={22}/></span>交易日课<small>DAILY DESK</small></a><div className="desk-date"><button aria-label="上一个记录日" disabled={!ready||dateIndex<=0} onClick={()=>archive&&select(dateList[dateIndex-1],archive)}><ChevronLeft size={17}/></button><label htmlFor="review-date" className="sr-only">复盘日期</label><input id="review-date" type="date" value={date} disabled={!ready} onChange={e=>archive&&select(e.target.value,archive)}/><button aria-label="下一个记录日" disabled={!ready||dateIndex>=dateList.length-1} onClick={()=>archive&&select(dateList[dateIndex+1],archive)}><ChevronRight size={17}/></button><button className="latest-date" disabled={!ready} onClick={()=>archive&&select(archive.latest,archive)}>最新</button></div><div className="desk-header-actions"><span className="save-indicator" role="status"><span/>{status}</span><details className="desk-tools"><summary aria-label="备份与数据工具"><Settings2 size={18}/><span>数据</span></summary><div><p>个人答案保存在当前浏览器。更换设备前请导出备份。</p><button onClick={backup}><Download size={16}/>导出完整备份</button><button onClick={()=>file.current?.click()}>导入 JSON 备份</button><a href={publicRoot} target="_blank" rel="noreferrer">打开复盘资料库 ↗</a></div></details></div><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value=''}}/></header>
 <div className="desk-layout"><RecapDirectory archive={archive} date={date} onSelect={d=>archive&&select(d,archive)}/>
 <main className="desk-main"><div className="desk-title"><div><h1>每日A股复盘</h1><p>市场与题材 → 当日复盘 → 决策考卷 → 汇总报告</p></div><button className="sync-button" disabled={syncing} onClick={()=>void sync(false,true)}><RefreshCw size={15} className={syncing?'spinning':''}/>{syncing?'同步资料中':'同步最新资料'}</button></div>
 <nav className="desk-main-jumps" aria-label="整页内容导航"><a href="#overview">市场图表</a><a href="#handbook">交易手册与工具</a><a href="#recap">当日复盘</a><a href="#exam">考卷</a><a href="#report">汇总报告</a></nav>
 {error&&<div className="error-panel" role="alert">{error}<div><button onClick={backup}>导出当前草稿 / 备份</button><button onClick={()=>void sync(!ready,true)}>重试读取</button></div></div>}{importNote&&<p role="status" className="desk-notice">{importNote}</p>}
 {!ready?<div className="desk-loading"><RefreshCw size={22} className="spinning"/><h2>正在准备当天的复盘资料</h2><p>读取市场数据、题材走势与已保存答卷。</p></div>:<>
 <section id="overview" className="market-section"><div className="market-date-row"><span>{date.replaceAll('-',' / ')}<b>盘后复盘</b></span><span className="data-status"><Check size={13}/>{day?(archive?.source==='live'?'同日复盘已同步':'已载入同日资料'):'等待当天复盘'}</span></div><div className="current-cycle"><div><span className="section-kicker">所选日情绪周期 · {date}</span><h2 className={tone(day?.label||'')}>{day?.label||'待当日复盘'}</h2><p>复盘原文标注{day?.url&&<> · <a href={day.url} target="_blank" rel="noreferrer">查看来源 ↗</a></>}</p></div><div className="my-cycle"><span>我的收盘判断</span><strong>{myCycle||'待填写'}</strong><a href="#exam">{myCycle?'修改判断':'填写考卷'} ↗</a></div></div><div className="overview-label"><h3>当日市场数据</h3><span>自动同步 · 保留原文口径</span></div><div className="market-strip">{metrics.map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>{archive?.syncNote&&<p className="desk-notice">{archive.syncNote}</p>}
 <div className="cycle-panel"><div className="cycle-heading"><div><h2>市场情绪周期节点</h2><p>原复盘节点与你的收盘判断按日期排列；点击切换整页。</p></div><label>观察范围<select aria-label="周期观察范围" value={range} onChange={e=>setRange(e.target.value)}><option value="20">所选日前后 20 个记录日</option><option value="60">所选日前后 60 个记录日</option><option value="all">全部周期</option></select></label></div><div className="cycle-track" ref={track}>{shown.map(d=><button key={d.date} aria-pressed={d.date===date} className={'cycle-node '+tone(d.label)+(d.date===date?' selected':'')} onClick={()=>select(d.date,archive!)}><time>{d.date.slice(5)}</time><span className="node-dot"/><strong>{d.label||'未标注'}</strong><small>{d.personal?'我的判断':'复盘原文'}</small></button>)}</div></div></section>
 <ThemeExplorer archive={archive!} anchor={date}/>
 <TradingRules/>
 <TradingHandbook/>
 <section id="recap" className="recap-content"><div className="section-heading"><div><span className="section-kicker">{date} / 复盘浓缩版</span><h2>当日复盘 · 六项速览</h2><p>大盘、情绪、题材梯队、关注标的、四种场景与交易预案。</p></div><a href="#exam" className="text-link">去做考卷 ↓</a></div><RecapDigest day={day}/>{day?<div className="recap-source-bar"><span>浓缩版来自同日复盘，完整原文保留在下方。</span><button aria-expanded={sourceOpen} onClick={()=>setSourceOpen(!sourceOpen)}>{sourceOpen?'收起原文':'展开完整原文'}<ChevronDown size={14}/></button><a href={day.url} target="_blank" rel="noreferrer">原页 ↗</a></div>:<div className="desk-empty">这一天的复盘还未发布。可以先写自己的判断，同日资料发布后会自动补充。</div>}
 {sourceOpen&&<div className="source-reader">{day?.sections?.map((s,i)=><article key={s.title}><button aria-expanded={chapter===i} onClick={()=>setChapter(chapter===i?null:i)}>{s.title}<ChevronDown size={15}/></button>{chapter===i&&<p>{s.text}</p>}</article>)}</div>}
 </section>
 <DailyQuestionnaire paper={paper} day={day} change={change} edit={edit}/>
 <section id="report" className="report-desk"><div className="section-heading"><div><span className="section-kicker">04 / 汇总与归档</span><h2>你的判断，汇成这一天的报告</h2><p>同日复盘作为资料底稿，个人答案补进相应章节。修改后自动更新。</p></div><span className={'report-state '+(paper.submitted?'submitted':'')}>{paper.submitted?'已归档':'填写中'}</span></div><div className="report-preview"><div className="report-preview-top"><BookOpen size={24}/><div><span>{date} / DAILY REVIEW</span><h3>{answer(paper,'f3')||'市场判断与交易复盘'}</h3></div></div><div className="conclusion-grid">{[['收盘周期',answer(paper,'f143')||answer(paper,'f5')],['我的主线',answer(paper,'f60')],['核心标的',answer(paper,'f170')],['仓位上限',answer(paper,'f116')]].map(([k,v])=><div key={k}><small>{k}</small><strong className={v?'':'pending-value'}>{v||'待你判断'}</strong></div>)}</div><div className="report-next"><small>明日预案</small><p>{paper.review?.next||'填写参与条件、退出信号和重点观察对象后，会自动出现在这里。'}</p></div><div className="report-footer"><span>{completed} / {dailyIds.length} 个日常问题已填 · 未填项会保留提示</span><button className="secondary-button" aria-expanded={showReport} onClick={()=>setShowReport(!showReport)}>{showReport?'收起完整报告':'展开完整报告 / 导出'}</button><button className="primary-button" onClick={submit}>{paper.submitted?'保存并查看报告':'交卷并归档'}<ArrowUpRight size={16}/></button></div></div>{showReport&&<Suspense fallback={<div className="desk-loading">正在整理完整报告…</div>}><DailyReport date={date} paper={paper} archive={archive!} onEdit={()=>document.getElementById('exam')?.scrollIntoView({behavior:'smooth'})}/></Suspense>}</section>
 </>}
 <footer className="desk-footer"><span>交易日课 · 资料自动整理，判断留给自己。</span><span>资料截至 {archive?.latest||'—'} · 页面打开时每 2 分钟检查更新</span></footer><details className="migration-note"><summary>备份与旧站迁移说明</summary><p>个人答案只保存在当前浏览器，不上传公开仓库。旧工作台的完整 JSON 备份可从右上角“数据”导入；本机已有个人作答的同日记录会保留。</p><a href="https://daily-trading-exam-raymond.raymond-blackfire.chatgpt.site/" target="_blank" rel="noreferrer">打开旧工作台导出备份 ↗</a></details>
 </main></div></div>
}
