import {useEffect,useRef,useState} from 'react';
import {BookOpen,Download,RefreshCw,ArrowUpRight,Check} from 'lucide-react';
import {sections,emptyPaper,validDate,chinaDate,type Paper} from '../model';
import {BlockView} from '../block-view';
import {loadArchive} from '../archive-client';
import {readRecords,saveRecord,importRecords,storageKey,type Saved} from '../local-records';
import {applyObjectiveFill} from '../autofill';
import {publicRoot,type Archive} from '../recap-source';
import SectorExplorer from './sector-explorer';
import DailyReport from './daily-report';
import './workspace.css';
import './onepage.css';
const tone=(s:string)=>/分歧|退潮|冰点/.test(s)?'cold':/回流|修复|反弹/.test(s)?'return':/高潮|主升|发酵/.test(s)?'warm':'neutral';
function download(name:string,value:unknown){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function Workspace(){
 const [archive,setArchive]=useState<Archive|null>(null),[records,setRecords]=useState<Saved[]>([]),[date,setDate]=useState(chinaDate()),[paper,setPaper]=useState<Paper>(emptyPaper),[ready,setReady]=useState(false),[status,setStatus]=useState('正在读取资料'),[error,setError]=useState(''),[syncing,setSyncing]=useState(false),[range,setRange]=useState('20'),[sourceOpen,setSourceOpen]=useState(true),[importNote,setImportNote]=useState('');
 const state=useRef({date:chinaDate(),paper:emptyPaper(),revision:0,dirty:false}),readyRef=useRef(false),archiveRef=useRef<Archive|null>(null),busy=useRef(false),blocked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),file=useRef<HTMLInputElement>(null),track=useRef<HTMLDivElement>(null);
 function flush(){const s=state.current;if(!s.dirty)return true;try{if(blocked.current)throw new Error('保存已暂停。请导出当前草稿，再刷新读取最新记录。');const saved=saveRecord(s.date,s.paper,s.revision);state.current={...s,revision:saved.revision,dirty:false};setRecords(readRecords());setStatus(s.paper.submitted?'已归档 · 保存在本机':'已自动保存到本机');setError('');return true}catch(e){blocked.current=true;setError((e as Error).message);setStatus('保存失败 · 请导出草稿');return false}}
 function select(d:string,a:Archive){if(!validDate(d)||!flush())return;try{const all=readRecords();setRecords(all);const saved=all.find(r=>r.date===d);const filled=applyObjectiveFill(saved?.paper||emptyPaper(),d,a);state.current={date:d,paper:filled.paper,revision:saved?.revision||0,dirty:filled.changed.length>0};setDate(d);setPaper(filled.paper);setStatus(filled.status==='archived'?'已归档 · 保留交卷时的答案':filled.status==='waiting'?'尚无可预填的同日资料':'同日客观项已核对');flush();const url=new URL(location.href);url.searchParams.set('date',d);history.replaceState(null,'',url)}catch(e){setError((e as Error).message)}}
 async function sync(initial=false){if(busy.current)return;busy.current=true;setSyncing(true);try{const a=await loadArchive();archiveRef.current=a;setArchive(a);if(initial){readRecords();const q=new URLSearchParams(location.search).get('date');const d=q&&validDate(q)?q:a.latest||chinaDate();select(d,a);readyRef.current=true;setReady(true);if(location.hash)setTimeout(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView(),150)}else if(readyRef.current&&!blocked.current)select(state.current.date,a)}catch(e){setError((e as Error).message)}finally{setSyncing(false);busy.current=false}}
 useEffect(()=>{void sync(true);const id=setInterval(()=>void sync(),120000);const focus=()=>void sync();const leave=(e:BeforeUnloadEvent)=>{if(!flush()){e.preventDefault();e.returnValue=''}};const external=(e:StorageEvent)=>{if(e.key!==storageKey||!readyRef.current)return;if(state.current.dirty){blocked.current=true;setError('另一标签页已更新记录。请先导出当前草稿，再刷新读取最新记录。')}else if(archiveRef.current)select(state.current.date,archiveRef.current)};window.addEventListener('focus',focus);window.addEventListener('beforeunload',leave);window.addEventListener('storage',external);return()=>{clearInterval(id);if(timer.current)clearTimeout(timer.current);window.removeEventListener('focus',focus);window.removeEventListener('beforeunload',leave);window.removeEventListener('storage',external)}},[]);
 function edit(next:Paper){state.current={...state.current,paper:{...next,submitted:false},dirty:true};setPaper(state.current.paper);setStatus('正在保存…');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(flush,500)}
 function change(k:string,v:string|string[]){edit({...state.current.paper,answers:{...state.current.paper.answers,[k]:v}})}
 function backup(){if(!flush()){download(state.current.date+'-未保存草稿.json',{records:[{...state.current}]});return}try{download('交易日课-完整备份-'+chinaDate()+'.json',{version:1,exportedAt:new Date().toISOString(),records:readRecords()})}catch{download('交易日课-原始记录.json',localStorage.getItem(storageKey))}}
 async function importFile(f:File){if(!flush())return;try{const result=importRecords(JSON.parse(await f.text()));setImportNote(`已导入 ${result.added} 天；保留本机已有答卷 ${result.skipped} 天。`);if(archiveRef.current)select(state.current.date,archiveRef.current)}catch(e){setError((e as Error).message)}}
 const day=archive?.days.find(d=>d.date===date);
 const nodes=new Map((archive?.days||[]).map(d=>[d.date,{date:d.date,label:d.label,original:d.label,personal:false}]));
 for(const r of [...records.filter(r=>r.date!==date),{date,paper}]){const label=r.paper.answers.f143||r.paper.answers.f5;if(typeof label==='string'&&label)nodes.set(r.date,{date:r.date,label,original:nodes.get(r.date)?.original||'',personal:true})}
 const days=[...nodes.values()].sort((a,b)=>a.date.localeCompare(b.date)),shown=range==='all'?days:days.slice(-Number(range));
 useEffect(()=>{const el=track.current?.querySelector<HTMLElement>('.selected');if(el&&track.current)track.current.scrollLeft=el.offsetLeft-track.current.offsetLeft-track.current.clientWidth/2+el.clientWidth/2},[date,range,ready]);
 const metricEntries=Object.entries(day?.metrics||{}).filter(([k,v],i,all)=>{const family=(n:string)=>/量能|成交额/.test(n)?'成交额':/极端腾落/.test(n)?'极端腾落':/腾落数/.test(n)?'腾落数':n;return !all.slice(0,i).some(([n,x])=>family(n)===family(k)&&x===v)});
 const autoCount=Object.entries(paper.autoFill||{}).filter(([id,v])=>paper.answers[id]===v.value).length;
 const blankReview={cycle:'',body:'',next:'',sectors:[]};
 return <div className="onepage"><header className="workbench-header"><a className="workbench-brand" href="./"><BookOpen size={22}/>交易日课<span>复盘 · 考卷 · 周期</span></a><a href={publicRoot} target="_blank" rel="noreferrer">复盘资料库 <ArrowUpRight size={15}/></a></header><main className="workbench-main"><div className="workbench-intro"><div><p className="eyebrow">DAILY TRADING WORKBENCH</p><h1>先看市场，再写自己的判断</h1><p className="muted">一份每日复盘，带出客观资料；一张考卷，汇成完整报告。</p></div><div className="date-picker"><label htmlFor="review-date">当前复盘日</label><input id="review-date" type="date" value={date} disabled={!ready} onChange={e=>archive&&select(e.target.value,archive)}/><button className="text-button" disabled={!ready} onClick={()=>archive&&select(archive.latest,archive)}>回到最新复盘</button></div></div>
 <nav className="step-nav"><a href="#recap">01 每日复盘</a><a href="#objective">02 周期与客观资料</a><a href="#exam">03 我的考卷</a><a href="#report">04 汇总报告</a><span aria-live="polite">{status}</span></nav>
 {error&&<div className="error-panel" role="alert">{error}<div><button onClick={backup}>导出当前草稿 / 备份</button></div></div>}
 <div className="storage-tools"><span>个人答卷保存在当前浏览器。更换设备前请导出备份。</span><button className="text-button" onClick={backup}><Download size={15}/>导出完整备份</button><button className="text-button" onClick={()=>file.current?.click()}>导入备份</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value=''}}/></div>{importNote&&<p role="status" className="data-note">{importNote}</p>}
 {!ready?<section className="hub-card loading-state">正在同步复盘资料…</section>:<>
 <section className="hub-card" id="recap"><div className="card-head"><div><p className="eyebrow">01 / 先完成每日 A 股复盘</p><h2>{date} · 每日市场复盘</h2><p>沿用复盘站同一天的原文。完成原站每日复盘并发布后，这里自动同步。</p></div><button className="secondary-button" disabled={syncing} onClick={()=>void sync()}><RefreshCw size={15}/>{syncing?'同步中':'同步最新复盘'}</button></div>
 {day?<><div className="recap-overview"><strong>{day.label||'原文未标注情绪阶段'}</strong><p>{day.summary}</p><a href={day.url} target="_blank" rel="noreferrer">查看同日复盘原页 ↗</a><small>原文观点供核对，不替你作答情绪阶段和主线判断。</small></div><div className="source-toolbar"><h3>当天复盘全文</h3><button className="text-button" onClick={()=>setSourceOpen(!sourceOpen)}>{sourceOpen?'收起全文':'展开全文'}</button></div>{sourceOpen&&<div className="source-chapters">{day.sections?.map((s,i)=><details open key={date+s.title+i}><summary>{s.title}</summary><div className="source-text">{s.text}</div></details>)}</div>}</>:<div className="note">这一天还没有公开复盘。你可以先写考卷；同日资料发布后会自动补全有来源的客观项。</div>}
 <details className="personal-supplement"><summary>补充我的复盘笔记 / 明日预案（仅保存在本机）</summary><label className="field">复盘补充<textarea value={paper.review?.body||''} maxLength={60000} onChange={e=>edit({...paper,review:{...blankReview,...paper.review,body:e.target.value}})}/></label><label className="field">明日预案<textarea value={paper.review?.next||''} maxLength={12000} onChange={e=>edit({...paper,review:{...blankReview,...paper.review,next:e.target.value}})}/></label></details></section>
 <section className="hub-card" id="objective"><div className="card-head"><div><p className="eyebrow">02 / 自动整理客观资料</p><h2>同日数据与整个周期</h2><p>数据和图表均随顶部日期切换。缺失值留空，保留原始口径。</p></div><span className="pill">{archive!.source==='live'?'已连接复盘站':'离线资料'} · 截至 {archive!.latest}</span></div>{archive!.syncNote&&<p className="data-note">{archive!.syncNote}</p>}<div className="objective-grid">{metricEntries.map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div>{!Object.keys(day?.metrics||{}).length&&<p className="note">当日客观指标尚未取得，等待同日复盘更新。</p>}<p className="data-note">考卷已预填 {autoCount} 项：有来源的最高板，以及按当日强度排序的前三个研究题材。其余客观资料集中展示于此；仓位、盈亏、主线和买卖判断由你填写。</p><div className="source-toolbar"><h3>市场情绪周期节点</h3><label>观察范围 <select value={range} onChange={e=>setRange(e.target.value)}><option value="20">近 20 个记录日</option><option value="60">近 60 个记录日</option><option value="all">全部周期</option></select></label></div><div className="cycle-track" ref={track}>{shown.map(d=><button key={d.date} className={'cycle-node '+tone(d.label)+(d.date===date?' selected':'')} onClick={()=>select(d.date,archive!)}><time>{d.date.slice(5)}</time><span className="node-dot"/><strong>{d.label||'未标注'}</strong><small title={d.original?'原文：'+d.original:undefined}>{d.personal?'我的收盘判断':'复盘原文'}</small></button>)}</div></section>
 <SectorExplorer archive={archive!} anchor={date} onAnchor={d=>select(d,archive!)}/>
 <section id="exam"><div className="exam-heading"><div><p className="eyebrow">03 / 留给自己的判断</p><h2>{date} · 每日决策考卷</h2><p className="muted">自动资料已就位。从上往下作答，报告同步整理。已确认 {paper.done.length} / {sections.length} 部分。</p></div><a href="#report" className="secondary-button">查看当前汇总 ↓</a></div><nav className="exam-shortcuts">{sections.map((s,i)=><a key={s.title} href={'#exam-'+i}>{paper.done.includes(i)?'✓ ':''}{s.title}</a>)}</nav>{sections.map((s,i)=><section className="hub-card exam-section" id={'exam-'+i} key={s.title}><div className="card-head"><h2>{s.title}</h2><label className="confirm-section"><input type="checkbox" checked={paper.done.includes(i)} onChange={e=>edit({...paper,done:e.target.checked?[...paper.done,i]:paper.done.filter(v=>v!==i)})}/>此部分已确认</label></div><div className="form-blocks">{s.blocks.map((b,j)=><div key={b.id||j}><BlockView b={b} answers={paper.answers} change={change}/>{b.id&&paper.autoFill?.[b.id]&&<p className="auto-source"><Check size={13}/>{paper.answers[b.id]===paper.autoFill[b.id].value?'已自动填入':'已手动调整，自动同步会保留'} · <a href={paper.autoFill[b.id].sourceUrl} target="_blank" rel="noreferrer">{paper.autoFill[b.id].sourceDate} 原文</a><span>{paper.autoFill[b.id].evidence}</span></p>}</div>)}</div></section>)}<div className="submit-bar"><div><strong>{paper.submitted?'考卷已归档':'完成考卷，汇总这一天'}</strong><p>{paper.submitted?'再次编辑会转为草稿。已归档答案不会被自动填充修改。':'允许保留待确认项；报告会明确标出待补充内容。'}</p></div><button className="primary-button" onClick={()=>{state.current={...state.current,paper:{...state.current.paper,submitted:true},dirty:true};setPaper(state.current.paper);if(flush())document.getElementById('report')?.scrollIntoView({behavior:'smooth'})}}>保存交卷并查看报告</button></div></section>
 <section id="report"><p className="eyebrow">04 / 当日统一报告</p><DailyReport date={date} paper={paper} archive={archive!} onEdit={()=>document.getElementById('exam')?.scrollIntoView({behavior:'smooth'})}/></section></>}
 <footer className="hub-foot">复盘站提供资料 · 考卷记录判断 · 同日汇成报告<span>打开页面时、回到页面时、保持打开每 2 分钟检查资料更新</span></footer><details className="migration-note"><summary>从旧工作台迁移答案</summary><p>在原考卷网站的历史答卷中导出完整 JSON 备份，再使用本页“导入备份”。已有个人作答的同日期记录会保留，不被导入覆盖。</p><a href="https://daily-trading-exam-raymond.raymond-blackfire.chatgpt.site/" target="_blank" rel="noreferrer">打开原考卷网站导出 ↗</a></details>
 </main></div>
}
